# Initially generated by GitHub Copilot.
"""Ensure imports under py/ resolve for scripts run from the repo root."""

from pathlib import Path
import sys


PY_DIR = Path(__file__).resolve().parent

if str(PY_DIR) not in sys.path:
    sys.path.insert(0, str(PY_DIR))
