# Initially generated by GitHub Copilot.
"""Update vendored files from sibling source repositories."""

import argparse
import datetime
import hashlib
import sys
from pathlib import Path

from cmn.utf8_io import force_utf8_io
from mb_cmn import vendoring_sync

import repo_paths

_REPO = repo_paths.repo_root()
_SOURCE_REPO = repo_paths.mam_basics_dir()
_SOURCE_PYCMN = _SOURCE_REPO / "py" / "mb_cmn"
_DEST_PYCMN = _REPO / "py" / "mb_cmn"
_SOURCE_PYMISC = _SOURCE_REPO / "py" / "mb_misc"
_DEST_PYMISC = _REPO / "py" / "mb_misc"
_SOURCE_MBDIFF = _SOURCE_REPO / "py" / "mb_diff_mpu"
_DEST_MBDIFF = _REPO / "py" / "mb_diff_mpu"

# UXLC data folders are vendored from the UXLC-utils sibling repo, not MAM-basics.
_UXLC_SOURCE_REPO = repo_paths.uxlc_utils_dir()
_SOURCE_UXLC39 = _UXLC_SOURCE_REPO / "in" / "UXLC-39"
_DEST_UXLC39 = repo_paths.in_dir() / "UXLC-39"
_SOURCE_UXLCMISC = _UXLC_SOURCE_REPO / "out" / "UXLC-misc"
_DEST_UXLCMISC = repo_paths.in_dir() / "UXLC-misc"


def main() -> None:
    args = _parse_args()
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

    _require_dir(_SOURCE_REPO)
    _require_dir(_SOURCE_PYCMN)
    _require_dir(_DEST_PYCMN)
    _require_dir(_SOURCE_PYMISC)
    _require_dir(_DEST_PYMISC)
    _require_dir(_SOURCE_MBDIFF)
    _require_dir(_DEST_MBDIFF)
    _require_dir(_UXLC_SOURCE_REPO)
    _require_dir(_SOURCE_UXLC39)
    _require_dir(_DEST_UXLC39)
    _require_dir(_SOURCE_UXLCMISC)
    _require_dir(_DEST_UXLCMISC)

    synced_pycmm, changed_pycmm = _sync(_SOURCE_PYCMN, _DEST_PYCMN, (".py",))
    synced_pymisc, changed_pymisc = _sync(_SOURCE_PYMISC, _DEST_PYMISC, (".py",))
    synced_mbdiff, changed_mbdiff = _sync(_SOURCE_MBDIFF, _DEST_MBDIFF, (".py",))
    synced_uxlc39, changed_uxlc39 = _sync(_SOURCE_UXLC39, _DEST_UXLC39, (".xml",))
    synced_uxlcmisc, changed_uxlcmisc = _sync(
        _SOURCE_UXLCMISC, _DEST_UXLCMISC, (".json",)
    )

    commit, tag = vendoring_sync.get_git_info(_SOURCE_REPO)
    uxlc_commit, uxlc_tag = vendoring_sync.get_git_info(_UXLC_SOURCE_REPO)
    date_str = datetime.date.today().isoformat()
    wrote_pycmm = _maybe_write_provenance(
        _DEST_PYCMN,
        source_rel="MAM-basics/py/mb_cmn",
        copied_files=synced_pycmm,
        commit=commit,
        tag=tag,
        date_str=date_str,
        changed=changed_pycmm,
        force=args.force_provenance,
    )
    wrote_pymisc = _maybe_write_provenance(
        _DEST_PYMISC,
        source_rel="MAM-basics/py/mb_misc",
        copied_files=synced_pymisc,
        commit=commit,
        tag=tag,
        date_str=date_str,
        changed=changed_pymisc,
        force=args.force_provenance,
    )
    wrote_mbdiff = _maybe_write_provenance(
        _DEST_MBDIFF,
        source_rel="MAM-basics/py/mb_diff_mpu",
        copied_files=synced_mbdiff,
        commit=commit,
        tag=tag,
        date_str=date_str,
        changed=changed_mbdiff,
        force=args.force_provenance,
    )
    wrote_uxlc39 = _maybe_write_provenance(
        _DEST_UXLC39,
        source_rel="UXLC-utils/in/UXLC-39",
        copied_files=synced_uxlc39,
        commit=uxlc_commit,
        tag=uxlc_tag,
        date_str=date_str,
        changed=changed_uxlc39,
        force=args.force_provenance,
    )
    wrote_uxlcmisc = _maybe_write_provenance(
        _DEST_UXLCMISC,
        source_rel="UXLC-utils/out/UXLC-misc",
        copied_files=synced_uxlcmisc,
        commit=uxlc_commit,
        tag=uxlc_tag,
        date_str=date_str,
        changed=changed_uxlcmisc,
        force=args.force_provenance,
    )

    _report(_DEST_PYCMN, synced_pycmm, changed_pycmm, wrote_pycmm)
    _report(_DEST_PYMISC, synced_pymisc, changed_pymisc, wrote_pymisc)
    _report(_DEST_MBDIFF, synced_mbdiff, changed_mbdiff, wrote_mbdiff)
    _report(_DEST_UXLC39, synced_uxlc39, changed_uxlc39, wrote_uxlc39)
    _report(_DEST_UXLCMISC, synced_uxlcmisc, changed_uxlcmisc, wrote_uxlcmisc)
    print(f"MAM-basics commit: {commit}")
    if tag:
        print(f"MAM-basics tag:    {tag}")
    print(f"UXLC-utils commit: {uxlc_commit}")
    if uxlc_tag:
        print(f"UXLC-utils tag:    {uxlc_tag}")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--force-provenance",
        action="store_true",
        help=(
            "Rewrite each _provenance.md even when no vendored file content changed. "
            "By default _provenance.md is left untouched (no date/commit bump) when "
            "the sync copied no new content."
        ),
    )
    return parser.parse_args()


def _sync(
    src_dir: Path, dest_dir: Path, suffixes: tuple[str, ...]
) -> tuple[list[str], bool]:
    """Copy src_dir into dest_dir, returning (copied_files, content_changed)."""
    before = _content_digest(dest_dir, suffixes)
    copied = vendoring_sync.copy_by_intersection(
        src_dir,
        dest_dir,
        include_suffixes=suffixes,
        strict=True,
    )
    changed = _content_digest(dest_dir, suffixes) != before
    return copied, changed


def _content_digest(dest_dir: Path, suffixes: tuple[str, ...]) -> dict[str, str]:
    """Map each matching dest filename to a hash of its bytes (non-recursive)."""
    digest: dict[str, str] = {}
    for path in dest_dir.iterdir():
        if not path.is_file() or "__pycache__" in path.parts:
            continue
        if path.suffix not in suffixes:
            continue
        digest[path.name] = hashlib.sha256(path.read_bytes()).hexdigest()
    return digest


def _maybe_write_provenance(
    dest_dir: Path,
    *,
    source_rel: str,
    copied_files,
    commit: str,
    tag: str | None,
    date_str: str,
    changed: bool,
    force: bool,
) -> bool:
    """Write _provenance.md only when content changed (or force). Return whether written."""
    if not (changed or force):
        return False
    vendoring_sync.write_provenance(
        dest_dir,
        source_rel=source_rel,
        copied_files=copied_files,
        commit=commit,
        tag=tag,
        date_str=date_str,
    )
    return True


def _report(dest_dir: Path, copied: list[str], changed: bool, wrote: bool) -> None:
    if wrote:
        provenance = "provenance updated" if changed else "provenance forced"
    else:
        provenance = "unchanged, provenance kept"
    print(f"{dest_dir.relative_to(_REPO)}: copied {len(copied)} files ({provenance})")


def _require_dir(path: Path) -> None:
    if not path.is_dir():
        raise FileNotFoundError(f"Directory does not exist: {path}")


if __name__ == "__main__":
    force_utf8_io()
    main()
