# Initially generated by GitHub Copilot.
"""Update vendored files from sibling source repositories."""

import datetime
import sys
from pathlib import Path

from mb_cmn import vendoring_sync

_REPO = Path(__file__).resolve().parents[1]
_SOURCE_REPO = _REPO.parent / "MAM-basics"
_SOURCE_PYCMN = _SOURCE_REPO / "py" / "mb_cmn"
_DEST_PYCMN = _REPO / "py" / "mb_cmn"
_SOURCE_MBDIFF = _SOURCE_REPO / "py" / "mb_diff_mpu"
_DEST_MBDIFF = _REPO / "py" / "mb_diff_mpu"


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")

    _require_dir(_SOURCE_REPO)
    _require_dir(_SOURCE_PYCMN)
    _require_dir(_DEST_PYCMN)
    _require_dir(_SOURCE_MBDIFF)
    _require_dir(_DEST_MBDIFF)

    synced_pycmm = vendoring_sync.copy_by_intersection(
        _SOURCE_PYCMN,
        _DEST_PYCMN,
        include_suffixes=(".py",),
        strict=True,
    )
    synced_mbdiff = vendoring_sync.copy_by_intersection(
        _SOURCE_MBDIFF,
        _DEST_MBDIFF,
        include_suffixes=(".py",),
        strict=True,
    )

    commit, tag = vendoring_sync.get_git_info(_SOURCE_REPO)
    date_str = datetime.date.today().isoformat()
    vendoring_sync.write_provenance(
        _DEST_PYCMN,
        source_rel="MAM-basics/py/mb_cmn",
        copied_files=synced_pycmm,
        commit=commit,
        tag=tag,
        date_str=date_str,
    )
    vendoring_sync.write_provenance(
        _DEST_MBDIFF,
        source_rel="MAM-basics/py/mb_diff_mpu",
        copied_files=synced_mbdiff,
        commit=commit,
        tag=tag,
        date_str=date_str,
    )

    print(f"{_DEST_PYCMN.relative_to(_REPO)}: copied {len(synced_pycmm)} files")
    print(f"{_DEST_MBDIFF.relative_to(_REPO)}: copied {len(synced_mbdiff)} files")
    print(f"MAM-basics commit: {commit}")
    if tag:
        print(f"MAM-basics tag:    {tag}")


def _require_dir(path: Path) -> None:
    if not path.is_dir():
        raise FileNotFoundError(f"Directory does not exist: {path}")


if __name__ == "__main__":
    main()
