# Initially generated by GitHub Copilot.
from __future__ import annotations

import argparse
from dataclasses import dataclass
import unittest


@dataclass(frozen=True)
class TestModuleSpec:
    flag: str
    module_name: str
    help_text: str


TEST_MODULE_SPECS = (
    TestModuleSpec(
        flag="accgram-filter-split-wlc",
        module_name="tests.test_accgram_filter_split_wlc",
        help_text="Run accgram filter-split provenance sidecar tests.",
    ),
    TestModuleSpec(
        flag="accgram-run-orig",
        module_name="tests.test_accgram_run_orig",
        help_text="Run accgram run-orig WSL invocation/pass-through tests.",
    ),
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Run repository tests through a single py/ entrypoint so module imports "
            "resolve consistently from repo root execution."
        )
    )
    for spec in TEST_MODULE_SPECS:
        parser.add_argument(
            f"--{spec.flag}",
            action="store_true",
            help=spec.help_text,
        )
    parser.add_argument(
        "--list",
        action="store_true",
        help="List available test selection flags and exit.",
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Run tests with higher verbosity.",
    )
    return parser


def selected_module_names(args: argparse.Namespace) -> list[str]:
    selected = [
        spec.module_name
        for spec in TEST_MODULE_SPECS
        if getattr(args, spec.flag.replace("-", "_"))
    ]
    if selected:
        return selected
    return [spec.module_name for spec in TEST_MODULE_SPECS]


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    if args.list:
        for spec in TEST_MODULE_SPECS:
            print(f"--{spec.flag}\t{spec.module_name}")
        return

    suite = unittest.TestSuite()
    loader = unittest.defaultTestLoader
    for module_name in selected_module_names(args):
        suite.addTests(loader.loadTestsFromName(module_name))

    runner = unittest.TextTestRunner(verbosity=2 if args.verbose else 1)
    result = runner.run(suite)
    raise SystemExit(0 if result.wasSuccessful() else 1)


if __name__ == "__main__":
    main()
