"""Legacy human-readable names for selected Unicode code points."""

import unicodedata

from mb_cmn import hebrew_accents as ha
from mb_cmn import hebrew_letters as hl
from mb_cmn import hebrew_points as hpo


def legacy_name(string_len_1):
    """Return the legacy human-readable Unicode name for a code point."""
    return _LEGACY_NAME_SHORTS.get(string_len_1) or unicodedata.name(string_len_1)


_LEGACY_NAME_SHORTS = {
    "\N{SPACE}": "space",
    "\N{COMBINING GRAPHEME JOINER}": "combining-grapheme-joiner",
    "\N{ZERO WIDTH JOINER}": "zero-width-joiner",
    ha.ATN: "etna\u1e25ta",
    "\N{HEBREW ACCENT SEGOL}": "segol-accent",
    "\N{HEBREW ACCENT SHALSHELET}": "shalshelet",
    "\N{HEBREW ACCENT ZAQEF QATAN}": "zaqef-qatan",
    "\N{HEBREW ACCENT ZAQEF GADOL}": "zaqef-gadol",
    ha.TIP: "tipe\u1e25a/tar\u1e25a",
    ha.REV: "revia",
    "\N{HEBREW ACCENT ZARQA}": "zarqa-stress-helper/tsinorit",
    "\N{HEBREW ACCENT PASHTA}": "pashta",
    "\N{HEBREW ACCENT YETIV}": "yetiv",
    "\N{HEBREW ACCENT TEVIR}": "tevir",
    ha.GER: "geresh",
    ha.GER_M: "geresh-muqdam",
    ha.GER_2: "gershayim",
    "\N{HEBREW ACCENT QARNEY PARA}": "qarney-para",
    ha.TEL_G: "telisha-gedola",
    "\N{HEBREW ACCENT PAZER}": "pazer",
    ha.ATN_H: "atna\u1e25-hafukh",
    ha.MUN: "muna\u1e25",
    "\N{HEBREW ACCENT MAHAPAKH}": "mahapakh",
    ha.MER: "merkha/yored",
    "\N{HEBREW ACCENT MERKHA KEFULA}": "merkha-kefula",
    "\N{HEBREW ACCENT DARGA}": "darga",
    "\N{HEBREW ACCENT QADMA}": "qadma",
    "\N{HEBREW ACCENT TELISHA QETANA}": "telisha-qetana",
    ha.YBY: "yera\u1e25-ben-yomo",
    ha.OLE: "ole",
    "\N{HEBREW ACCENT ILUY}": "iluy",
    "\N{HEBREW ACCENT DEHI}": "de\u1e25i",
    "\N{HEBREW ACCENT ZINOR}": "tsinor",
    hpo.SHEVA: "sheva",
    hpo.XSEGOL: "\u1e25ataf-segol",
    hpo.XPATAX: "\u1e25ataf-pata\u1e25",
    hpo.XQAMATS: "\u1e25ataf-qamats",
    hpo.XIRIQ: "\u1e25iriq",
    hpo.TSERE: "tsere",
    hpo.SEGOL_V: "segol-vowel",
    hpo.PATAX: "pata\u1e25",
    hpo.QAMATS: "qamats",
    hpo.XOLAM: "\u1e25olam",
    hpo.XOLAM_XFV: "\u1e25olam-\u1e25aser-for-vav",
    hpo.QUBUTS: "qubuts",
    hpo.DAGOMOSD: "dagesh/mapiq/shuruq-dot",
    hpo.MTGOSLQ: "meteg/siluq",
    "\N{HEBREW PUNCTUATION MAQAF}": "maqaf",
    hpo.RAFE: "rafeh",
    "\N{HEBREW PUNCTUATION PASEQ}": "paseq/legarmeih",
    hpo.SHIND: "shin-dot",
    hpo.SIND: "sin-dot",
    "\N{HEBREW PUNCTUATION SOF PASUQ}": "sof-pasuq",
    "\N{HEBREW MARK UPPER DOT}": "upper-dot",
    "\N{HEBREW MARK LOWER DOT}": "lower-dot",
    "\N{HEBREW PUNCTUATION NUN HAFUKHA}": "nun-hafukha",
    hpo.QAMATS_Q: "qamats-qatan",
    hl.ALEF: "alef",
    hl.BET: "bet",
    hl.GIMEL: "gimel",
    hl.DALET: "dalet",
    hl.HE: "he",
    hl.VAV: "vav",
    hl.ZAYIN: "zayin",
    hl.XET: "\u1e25et",
    hl.TET: "tet",
    hl.YOD: "yod",
    hl.FKAF: "final-kaf",
    hl.KAF: "kaf",
    hl.LAMED: "lamed",
    hl.FMEM: "final-mem",
    hl.MEM: "mem",
    hl.FNUN: "final-nun",
    hl.NUN: "nun",
    hl.SAMEKH: "samekh",
    hl.AYIN: "ayin",
    hl.FPE: "final-pe",
    hl.PE: "pe",
    hl.FTSADI: "final-tsadi",
    hl.TSADI: "tsadi",
    hl.QOF: "qof",
    hl.RESH: "resh",
    hl.SHIN: "shin",
    hl.TAV: "tav",
    hpo.VARIKA: "varika",
}
