# Initially generated by GitHub Copilot.

from __future__ import annotations

import json
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from types import SimpleNamespace

from accgram import filter_split_wlc


class TestAccgramFilterSplitWlc(unittest.TestCase):
    def test_run_writes_native_provenance_json_sidecar(self):
        with TemporaryDirectory() as tmp_dir:
            split_out_dir = Path(tmp_dir) / "raw"
            out_dir = Path(tmp_dir) / "filtered"
            troublemakers_out = Path(tmp_dir) / "out" / "accgram" / "goerwitz" / "_troublemakers.json"
            input_path = Path(tmp_dir) / "wlc422_ps.txt"
            input_path.write_text(
                "ob1:1 Troublemaker verse payload\n"
                "ob1:2 Normal verse payload\n",
                encoding="utf-8",
            )
            calls: list[tuple[Path, Path, object]] = []

            def fake_split_wlc_to_books(input_path, out_dir, keep_line_fn):
                calls.append((input_path, out_dir, keep_line_fn))
                if keep_line_fn is None:
                    return SimpleNamespace(
                        verses_seen=3,
                        verses_excluded=0,
                        books_written=3,
                        verses_written=3,
                        book_order=["gn", "ps", "pr"],
                    )

                self.assertFalse(keep_line_fn("ps", 1, 1))
                self.assertTrue(keep_line_fn("gn", 1, 1))
                self.assertFalse(keep_line_fn("pr", 1, 1))
                self.assertFalse(keep_line_fn("ob", 1, 1))
                return SimpleNamespace(
                    verses_seen=4,
                    verses_excluded=3,
                    books_written=1,
                    verses_written=1,
                    book_order=["gn"],
                )

            args = SimpleNamespace(
                input=input_path,
                split_out_dir=split_out_dir,
                out_dir=out_dir,
                troublemakers_out=troublemakers_out,
            )
            filter_split_wlc.run(args, fake_split_wlc_to_books)

            self.assertEqual(len(calls), 2)
            self.assertEqual(calls[0][1], split_out_dir)
            self.assertIsNone(calls[0][2])
            self.assertEqual(calls[1][1], out_dir)
            self.assertIsNotNone(calls[1][2])

            split_provenance_path = split_out_dir / "_provenance.json"
            self.assertTrue(split_provenance_path.exists())

            split_payload = json.loads(split_provenance_path.read_text(encoding="utf-8"))
            self.assertEqual(
                split_payload["provenance"],
                "This file was generated by wlc-utils/py/accgram/filter_split_wlc.py.",
            )
            self.assertEqual(split_payload["artifacts_description"], "unfiltered WLC split outputs")
            self.assertEqual(split_payload["summary"]["verses_seen"], 3)
            self.assertEqual(split_payload["summary"]["verses_written"], 3)
            self.assertEqual(split_payload["summary"]["books_written"], 3)
            self.assertNotIn("verses_excluded", split_payload["summary"])
            self.assertNotIn("books_fully_excluded", split_payload)
            self.assertNotIn("books_partially_excluded", split_payload)

            provenance_path = out_dir / "_provenance.json"
            self.assertTrue(provenance_path.exists())
            self.assertFalse((out_dir / "filtered-out.json").exists())

            payload = json.loads(provenance_path.read_text(encoding="utf-8"))
            self.assertEqual(
                payload["provenance"],
                "This file was generated by wlc-utils/py/accgram/filter_split_wlc.py.",
            )
            self.assertEqual(
                payload["artifacts_description"],
                "filtered WLC split outputs and exclusion diagnostics",
            )
            self.assertEqual(payload["summary"]["verses_seen"], 4)
            self.assertEqual(payload["summary"]["verses_excluded"], 3)
            self.assertIn("ps", payload["books_fully_excluded"])

            self.assertTrue(troublemakers_out.exists())
            troublemakers_payload = json.loads(troublemakers_out.read_text(encoding="utf-8"))
            self.assertEqual(
                troublemakers_payload["artifacts_description"],
                "hardcoded troublemaker verse exclusions",
            )
            self.assertEqual(
                troublemakers_payload["troublemakers"],
                [{"ref": "ob 1:1", "content": "Troublemaker verse payload"}],
            )
            self.assertFalse(
                any(item["ref"] == "ps 1:1" for item in troublemakers_payload["troublemakers"])
            )

    def test_run_rejects_same_output_directories(self):
        with TemporaryDirectory() as tmp_dir:
            out_dir = Path(tmp_dir) / "out"
            input_path = Path(tmp_dir) / "wlc422_ps.txt"
            input_path.write_text("dummy", encoding="utf-8")
            troublemakers_out = Path(tmp_dir) / "_troublemakers.json"

            args = SimpleNamespace(
                input=input_path,
                split_out_dir=out_dir,
                out_dir=out_dir,
                troublemakers_out=troublemakers_out,
            )
            with self.assertRaisesRegex(ValueError, "must be different directories"):
                filter_split_wlc.run(args, lambda input_path, out_dir, keep_line_fn=None: None)

    def test_should_keep_line_filters_only_configured_troublemaker_ref(self):
        self.assertFalse(filter_split_wlc.should_keep_line("ob", 1, 1))
        self.assertFalse(filter_split_wlc.should_keep_line("je", 9, 11))
        self.assertFalse(filter_split_wlc.should_keep_line("ju", 13, 18))
        self.assertTrue(filter_split_wlc.should_keep_line("ob", 1, 2))


if __name__ == "__main__":
    unittest.main()
