# Initially generated by GitHub Copilot.

from __future__ import annotations

import json
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path
from tempfile import TemporaryDirectory
from types import SimpleNamespace

from accgram.hebrew_verse_sanitize import sanitize_verse_text_payload
from accgram import mam_simple_diff
from accgram import mam_simple_verse
from accgram import research_tms
from accgram import research_tms_report
from accgram import research_tms_report_subsets
from accgram import troublemaker_structured_text_sanity
from accgram import verse_json_smart_concat
from accgram import wlc_uxlc_diff


class TestAccgramResearchTroublemakers(unittest.TestCase):
    def test_smart_concatenate_string_runs_joins_with_space_without_maqaf(self):
        out = verse_json_smart_concat.smart_concatenate_string_runs(
            ["אב", "גד", {"x": 1}, "דה", "וז"]
        )

        self.assertEqual(out, ["אב גד", {"x": 1}, "דה וז"])

    def test_smart_concatenate_string_runs_joins_without_space_after_maqaf(self):
        out = verse_json_smart_concat.smart_concatenate_string_runs(["אב־", "גד", "דה"])

        self.assertEqual(out, ["אב־גד דה"])

    def test_smart_concatenate_string_runs_allows_multi_token_run(self):
        out = verse_json_smart_concat.smart_concatenate_string_runs(["אב", "גד", "דה"])

        self.assertEqual(out, ["אב גד דה"])

    def test_smart_concatenate_string_runs_attaches_paseq_to_previous_word(self):
        out = verse_json_smart_concat.smart_concatenate_string_runs(["אב", "׀", "גד"])

        self.assertEqual(out, ["אב׀ גד"])

    def test_smart_concatenate_string_runs_asserts_on_preexisting_space(self):
        with self.assertRaises(AssertionError):
            verse_json_smart_concat.smart_concatenate_string_runs(["אב ג", "דה"])

    def test_smart_concatenate_row_for_json_does_not_touch_diff(self):
        row = {
            "wlc422_kq_u_verse": {"vels": ["אב", "גד"]},
            "uxlc_verse": ["אב", "גד"],
            "diff_wlc_uxlc": [{"wlc422": ["אב"], "uxlc": ["אג"]}],
            "mam_simple_verse": {"vels": ["אב", "גד"]},
            "diff_wlc_mam": [{"wlc422": ["אב"], "mam_simple": ["אג"]}],
        }

        out = verse_json_smart_concat.smart_concatenate_row_for_json(row)

        self.assertEqual(out["wlc422_kq_u_verse"], {"vels": ["אב גד"]})
        self.assertEqual(out["uxlc_verse"], ["אב גד"])
        self.assertEqual(out["diff_wlc_uxlc"], row["diff_wlc_uxlc"])
        self.assertEqual(out["mam_simple_verse"], {"vels": ["אב גד"]})
        self.assertEqual(out["diff_wlc_mam"], row["diff_wlc_mam"])

    def test_load_wlc422_index_collapses_notes_list_to_string(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            wlc422_dir = base / "wlc422-kq-u"
            wlc422_dir.mkdir(parents=True, exist_ok=True)

            (wlc422_dir / "1verses_00_ex.json").write_text(
                json.dumps(
                    [
                        {
                            "bcv": "ex34:6",
                            "vels": [
                                "ויעבר",
                                {"word": "ואמת", "notes": ["]c", "]n", "]p"]},
                            ],
                        }
                    ],
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            index = research_tms._load_wlc422_index(wlc422_dir)

            self.assertEqual(
                index["ex34:6"]["vels"][1],
                {"word": "ואמת", "notes": "]c]n]p"},
            )

    def test_load_mam_simple_for_refs_and_diff_wlc_mam(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            mam_simple_dir = base / "mam-simple"
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            (mam_simple_dir / "Gen.json").write_text(
                json.dumps(
                    {
                        "versification-tradition": "vtbhs",
                        "contents": [
                            {
                                "type": "book39",
                                "osisID": "Gen",
                                "contents": [
                                    {
                                        "type": "chapter",
                                        "osisID": "Gen.1",
                                        "contents": [
                                            {
                                                "type": "verse",
                                                "osisID": "Gen.1.1",
                                                "contents": [
                                                    {"type": "text", "text": "אב־"},
                                                    {"type": "text", "text": "גד"},
                                                    {"type": "lp-paseq"},
                                                    {
                                                        "type": "kq",
                                                        "contents": [
                                                            {
                                                                "type": "kq-k",
                                                                "contents": [
                                                                    {
                                                                        "type": "text",
                                                                        "text": "כתיב",
                                                                    }
                                                                ],
                                                            },
                                                            {
                                                                "type": "kq-q",
                                                                "contents": [
                                                                    {
                                                                        "type": "text",
                                                                        "text": "קְרֵי",
                                                                    }
                                                                ],
                                                            },
                                                        ],
                                                    },
                                                    {"type": "text", "text": " דה־ו"},
                                                ],
                                            }
                                        ],
                                    }
                                ],
                            }
                        ],
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            loaded = mam_simple_verse.load_mam_simple_for_refs(
                mam_simple_dir, {"gn": {(1, 1)}}
            )

            self.assertIn("gn1:1", loaded)
            self.assertEqual(
                loaded["gn1:1"]["mam_simple_verse"]["vels"],
                ["אב־", "גד", "׀", "קְרֵי", "דה־", "ו"],
            )

            diff = mam_simple_diff.diff_wlc_mam(
                {"vels": ["אב־", "גד", "קְרֵי", "דה־ו"]},
                loaded["gn1:1"]["mam_simple_verse"],
            )

            self.assertIsInstance(diff, list)
            self.assertGreaterEqual(len(diff), 1)
            self.assertIn("mam_simple", diff[0])

    def test_diff_wlc_uxlc_simplifies_uxlc_note_only_delta(self):
        diff = wlc_uxlc_diff.diff_wlc_uxlc(
            {"vels": ["foo"]},
            [{"text": "foo", "note": "bar"}],
        )

        self.assertEqual(diff, {"uxlc_adds_note": "bar"})

    def test_diff_wlc_uxlc_simplifies_note_only_delta(self):
        diff = wlc_uxlc_diff.diff_wlc_uxlc(
            {"vels": [{"word": "foo", "notes": ["]Q", "]n", "]p"]}]},
            ["foo"],
        )

        self.assertEqual(diff, {"wlc_adds_notes": ["]Q", "]n", "]p"]})

    def test_diff_wlc_uxlc_reports_token_changes(self):
        diff = wlc_uxlc_diff.diff_wlc_uxlc(
            {"vels": ["a", "b", "c"]},
            ["a", "x", "c"],
        )

        self.assertEqual(diff, {"wlc422": "b", "uxlc": "x"})

    def test_diff_wlc_mam_normalizes_standalone_paseq_tokenization(self):
        diff = mam_simple_diff.diff_wlc_mam(
            {"vels": ["אב׀", "גד"]},
            {"vels": ["אב", "׀", "גד"]},
        )

        self.assertEqual(diff, [])

    def test_diff_wlc_mam_reports_token_changes_as_scalars_for_singletons(self):
        diff = mam_simple_diff.diff_wlc_mam(
            {"vels": ["a", "b", "c"]},
            {"vels": ["a", "x", "c"]},
        )

        self.assertEqual(diff, {"wlc422": "b", "mam_simple": "x"})

    def test_diff_wlc_uxlc_keeps_list_when_multiple_diffs(self):
        diff = wlc_uxlc_diff.diff_wlc_uxlc(
            {"vels": ["a", "b", "c", "d", "e"]},
            ["a", "x", "c", "y", "e"],
        )

        self.assertEqual(
            diff, [{"wlc422": "b", "uxlc": "x"}, {"wlc422": "d", "uxlc": "y"}]
        )

    def test_diff_wlc_mam_keeps_list_when_multiple_diffs(self):
        diff = mam_simple_diff.diff_wlc_mam(
            {"vels": ["a", "b", "c", "d", "e"]},
            {"vels": ["a", "x", "c", "y", "e"]},
        )

        self.assertEqual(
            diff,
            [{"wlc422": "b", "mam_simple": "x"}, {"wlc422": "d", "mam_simple": "y"}],
        )

    def test_to_xmlish_word_preserves_text_after_inline_x_child(self):
        element = ET.fromstring("<w>פֶ֛<x>t</x>לִאי׃</w>")

        node = research_tms._to_xmlish_verse_child(element)
        node = sanitize_verse_text_payload(node)

        self.assertIsInstance(node, dict)
        self.assertEqual(node, {"text": "פ֛לאי׃", "note": "t"})

    def test_sanitize_keeps_only_last_meteg_in_last_word(self):
        wlc422_verse = {
            "bcv": "gn1:1",
            "vels": ["אֽב", "גֽדֽה"],
        }
        uxlc_nodes = ["אֽב", "גֽדֽה"]

        wlc_clean = sanitize_verse_text_payload(wlc422_verse)
        uxlc_clean = sanitize_verse_text_payload(uxlc_nodes)

        self.assertEqual(wlc_clean["vels"], ["אב", "גדֽה"])
        self.assertEqual(uxlc_clean, ["אב", "גדֽה"])

    def test_sanitize_option_removes_duplicate_telisha_gedola(self):
        node = {"vels": ["א֠ת֠י", "ל֠מ֠ען", "ב֠כנפ֠ו"]}

        default_clean = sanitize_verse_text_payload(node)
        mam_clean = sanitize_verse_text_payload(
            node,
            remove_duplicate_telisha_gedola=True,
        )

        self.assertEqual(default_clean["vels"], ["א֠ת֠י", "ל֠מ֠ען", "ב֠כנפ֠ו"])
        self.assertEqual(mam_clean["vels"], ["א֠תי", "ל֠מען", "ב֠כנפו"])

    def test_run_happy_path_enriches_both_sources(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            mam_simple_dir = base / "mam-simple"
            out_path = base / "out" / "research-troublemakers.json"
            html_out = base / "gh-pages" / "accgram" / "goerwitz-tms.html"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps(
                    {
                        "troublemakers": [
                            {
                                "ref": "gn 1:1",
                                "content": "payload",
                            }
                        ]
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text(
                json.dumps(
                    [
                        {
                            "bcv": "gn1:1",
                            "vels": ["בְּרֵאשִׁ֖ית", {"sam_pe_inun": "P"}, "בָּרָ֣א"],
                        }
                    ],
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (uxlc_dir / "Genesis.xml").write_text(
                """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Tanach>
  <c n=\"1\">
    <v n=\"1\">
      <w>בְּרֵאשִׁ֖ית<s t=\"large\">ע</s><x>5</x></w>
      <k>כתיב</k>
      <q>קְרֵי</q>
      <samekh/>
    </v>
  </c>
</Tanach>
""",
                encoding="utf-8",
            )
            (mam_simple_dir / "Gen.json").write_text(
                json.dumps(
                    {
                        "versification-tradition": "vtbhs",
                        "contents": [
                            {
                                "type": "book39",
                                "osisID": "Gen",
                                "contents": [
                                    {
                                        "type": "chapter",
                                        "osisID": "Gen.1",
                                        "contents": [
                                            {
                                                "type": "verse",
                                                "osisID": "Gen.1.1",
                                                "contents": [
                                                    {"type": "text", "text": "אב־"},
                                                    {"type": "text", "text": "גד"},
                                                    {"type": "lp-paseq"},
                                                    {
                                                        "type": "kq",
                                                        "contents": [
                                                            {
                                                                "type": "kq-k",
                                                                "contents": [
                                                                    {
                                                                        "type": "text",
                                                                        "text": "כתיב",
                                                                    }
                                                                ],
                                                            },
                                                            {
                                                                "type": "kq-q",
                                                                "contents": [
                                                                    {
                                                                        "type": "text",
                                                                        "text": "קְרֵי",
                                                                    }
                                                                ],
                                                            },
                                                        ],
                                                    },
                                                    {"type": "text", "text": " דה־ו"},
                                                ],
                                            }
                                        ],
                                    }
                                ],
                            }
                        ],
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            research_tms.run(
                SimpleNamespace(
                    troubles_in=troubles_in,
                    wlc422_kq_u_dir=wlc422_dir,
                    uxlc_dir=uxlc_dir,
                    mam_simple_dir=mam_simple_dir,
                    out=out_path,
                )
            )

            self.assertTrue(out_path.exists())
            payload = json.loads(out_path.read_text(encoding="utf-8"))
            self.assertEqual(
                payload["provenance"],
                "This file was generated by wlc-utils/py/accgram/research_tms.py.",
            )
            self.assertEqual(payload["summary"]["troublemakers"], 1)

            row = payload["troublemakers"][0]
            self.assertEqual(row["ref"], "gn 1:1")
            self.assertEqual(row["wlc422_kq_u_verse"]["vels"][0], "בראש֖ית בר֣א")
            self.assertIn(type(row["diff_wlc_uxlc"]), (dict, list))
            if isinstance(row["diff_wlc_uxlc"], list):
                self.assertGreaterEqual(len(row["diff_wlc_uxlc"]), 1)
            self.assertFalse(
                any(
                    isinstance(token, dict) and set(token.keys()) == {"sam_pe_inun"}
                    for token in row["wlc422_kq_u_verse"]["vels"]
                )
            )

            xmlish = row["uxlc_verse"]
            self.assertEqual(xmlish[0]["tag"], "w")
            self.assertEqual(xmlish[0]["text"], "בראש֖ית")
            self.assertEqual(xmlish[1], "קרי")
            self.assertFalse(
                any(
                    isinstance(node, dict) and node.get("tag") in {"pe", "samekh"}
                    for node in xmlish
                )
            )
            self.assertEqual(xmlish[0]["children"][0]["tag"], "s")
            self.assertEqual(xmlish[0]["children"][0]["attrs"]["t"], "large")
            self.assertEqual(xmlish[0]["children"][1]["tag"], "x")
            self.assertEqual(xmlish[0]["children"][1]["text"], "5")

            self.assertEqual(row["mam_simple_verse"]["vels"], ["אב־גד׀ קרי דה־ו"])
            self.assertIn(type(row["diff_wlc_mam"]), (dict, list))
            if isinstance(row["diff_wlc_mam"], list):
                self.assertGreaterEqual(len(row["diff_wlc_mam"]), 1)
                first_diff = row["diff_wlc_mam"][0]
            else:
                first_diff = row["diff_wlc_mam"]
            self.assertIn("mam_simple", first_diff)

            self.assertTrue(html_out.exists())
            self.assertTrue((html_out.parent / "goerwitz-tms-msp-y.html").exists())
            self.assertTrue((html_out.parent / "goerwitz-tms-msp-n.html").exists())
            html_text = html_out.read_text(encoding="utf-8")
            html_text_compact = "".join(html_text.split())

            self.assertIn('class="goerwitz-tms-width-limited"', html_text)
            self.assertIn("<h2>Introduction</h2>", html_text_compact)
            self.assertIn("<h2>Subsets</h2>", html_text_compact)
            self.assertIn(
                '<li><ahref="goerwitz-tms-msp-y.html">missingsofpasuq:yes</a></li>',
                html_text_compact,
            )
            self.assertIn(
                '<li><ahref="goerwitz-tms-msp-n.html">missingsofpasuq:no</a></li>',
                html_text_compact,
            )
            self.assertIn(
                "These1versescausedtroublefortheGoerwitzaccentgrammarchecker.",
                html_text_compact,
            )
            self.assertIn("WLCquirks,LCquirks,andcheckerquirks", html_text_compact)
            self.assertIn("StudiesinAncientOrientalCivilization60", html_text_compact)
            self.assertIn(
                '<ahref="'
                "https://isac.uchicago.edu/research/publications/saoc/"
                'saoc-60-studies-semitic-and-afroasiatic-linguistics-presented-gene-b"'
                ">"
                "StudiesinAncientOrientalCivilization60"
                "</a>",
                html_text_compact,
            )
            self.assertIn("<h2>WLCBracketNotes</h2>", html_text_compact)
            self.assertIn("Nobracket-notetokensdetectedonthispage.", html_text_compact)
            self.assertIn('<h2id="tmgn1v1">gn1:1</h2>', html_text_compact)
            self.assertIn('href="#tmgn1v1"', html_text)
            self.assertIn("🔗", html_text)
            self.assertIn(
                "https://bdenckla.github.io/MAM-with-doc/A1-Genesis.html#c1v1",
                html_text,
            )
            self.assertIn("https://tanach.us/Tanach.xml?Gen1:1", html_text)
            self.assertNotIn("UXLCchange:none", html_text_compact)
            self.assertIn("<th>value</th><th></th><th>key</th>", html_text_compact)
            self.assertIn(
                '<tdlang="hbo"dir="rtl">בראש֖יתבר֣א</td><td></td><td>wlc_before</td>',
                html_text_compact,
            )
            self.assertIn("<td></td><td></td><td>wlc_focus</td>", html_text_compact)
            self.assertIn("<td></td><td></td><td>wlc_after</td>", html_text_compact)
            intro_heading_idx = html_text_compact.index("<h2>Introduction</h2>")
            bracket_heading_idx = html_text_compact.index("<h2>WLCBracketNotes</h2>")
            first_verse_heading_idx = html_text_compact.index(
                '<h2id="tmgn1v1">gn1:1</h2>'
            )
            self.assertLess(intro_heading_idx, first_verse_heading_idx)
            self.assertLess(bracket_heading_idx, first_verse_heading_idx)
            before_idx = html_text_compact.index(
                '<tdlang="hbo"dir="rtl">בראש֖יתבר֣א</td><td></td><td>wlc_before</td>'
            )
            wlc_focus_idx = html_text_compact.index(
                "<td></td><td></td><td>wlc_focus</td>"
            )
            after_idx = html_text_compact.index("<td></td><td></td><td>wlc_after</td>")
            self.assertLess(before_idx, wlc_focus_idx)
            self.assertLess(wlc_focus_idx, after_idx)

    def test_run_writes_enriched_research_oddballs_json(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            oddballs_in = base / "in" / "_oddballs.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            mam_simple_dir = base / "mam-simple"
            out_path = base / "out" / "research-troublemakers.json"
            oddballs_out = base / "out" / "research-oddballs.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps({"troublemakers": []}, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            oddballs_in.write_text(
                json.dumps(
                    {
                        "oddballs": [
                            {
                                "ref": "gn 1:1",
                                "content": "oddball payload",
                                "output_file": "wlc_422_ps_gn_ag.txt",
                            }
                        ]
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text(
                json.dumps(
                    [
                        {
                            "bcv": "gn1:1",
                            "vels": ["בְּרֵאשִׁ֖ית", "בָּרָ֣א"],
                        }
                    ],
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (uxlc_dir / "Genesis.xml").write_text(
                """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Tanach>
  <c n=\"1\">
    <v n=\"1\">
      <w>בְּרֵאשִׁ֖ית</w>
      <w>בָּרָ֣א</w>
    </v>
  </c>
</Tanach>
""",
                encoding="utf-8",
            )
            (mam_simple_dir / "Gen.json").write_text(
                json.dumps(
                    {
                        "versification-tradition": "vtbhs",
                        "contents": [
                            {
                                "type": "book39",
                                "osisID": "Gen",
                                "contents": [
                                    {
                                        "type": "chapter",
                                        "osisID": "Gen.1",
                                        "contents": [
                                            {
                                                "type": "verse",
                                                "osisID": "Gen.1.1",
                                                "contents": [
                                                    {
                                                        "type": "text",
                                                        "text": "בְּרֵאשִׁ֖ית",
                                                    },
                                                    {
                                                        "type": "text",
                                                        "text": "בָּרָ֣א",
                                                    },
                                                ],
                                            }
                                        ],
                                    }
                                ],
                            }
                        ],
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            research_tms.run(
                SimpleNamespace(
                    troubles_in=troubles_in,
                    oddballs_in=oddballs_in,
                    wlc422_kq_u_dir=wlc422_dir,
                    uxlc_dir=uxlc_dir,
                    mam_simple_dir=mam_simple_dir,
                    out=out_path,
                    oddballs_out=oddballs_out,
                )
            )

            self.assertTrue(out_path.exists())
            self.assertTrue(oddballs_out.exists())

            troubles_payload = json.loads(out_path.read_text(encoding="utf-8"))
            self.assertEqual(troubles_payload["summary"]["troublemakers"], 0)

            oddballs_payload = json.loads(oddballs_out.read_text(encoding="utf-8"))
            self.assertEqual(
                oddballs_payload["artifacts_description"],
                "enriched oddball verse research records",
            )
            self.assertEqual(oddballs_payload["summary"]["oddballs"], 1)
            oddball_row = oddballs_payload["oddballs"][0]
            self.assertEqual(oddball_row["ref"], "gn 1:1")
            self.assertEqual(oddball_row["content"], "oddball payload")
            self.assertIn("wlc422_kq_u_verse", oddball_row)
            self.assertIn("uxlc_verse", oddball_row)
            self.assertIn("diff_wlc_uxlc", oddball_row)
            self.assertIn("mam_simple_verse", oddball_row)
            self.assertIn("diff_wlc_mam", oddball_row)
            self.assertNotIn("structured_text", oddball_row)

    def test_run_ignores_note_only_wlc_uxlc_and_wlc_mam_diffs(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            mam_simple_dir = base / "mam-simple"
            out_path = base / "out" / "research-troublemakers.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps(
                    {
                        "troublemakers": [
                            {
                                "ref": "gn 1:1",
                                "content": "payload",
                            }
                        ]
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text(
                json.dumps(
                    [
                        {
                            "bcv": "gn1:1",
                            "vels": [
                                {
                                    "word": "אב",
                                    "notes": ["]Q"],
                                }
                            ],
                        }
                    ],
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (uxlc_dir / "Genesis.xml").write_text(
                """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Tanach>
  <c n=\"1\">
    <v n=\"1\">
      <w>אב<x>m</x></w>
    </v>
  </c>
</Tanach>
""",
                encoding="utf-8",
            )
            (mam_simple_dir / "Gen.json").write_text(
                json.dumps(
                    {
                        "versification-tradition": "vtbhs",
                        "contents": [
                            {
                                "type": "book39",
                                "osisID": "Gen",
                                "contents": [
                                    {
                                        "type": "chapter",
                                        "osisID": "Gen.1",
                                        "contents": [
                                            {
                                                "type": "verse",
                                                "osisID": "Gen.1.1",
                                                "contents": [
                                                    {
                                                        "type": "text",
                                                        "text": "אב",
                                                    }
                                                ],
                                            }
                                        ],
                                    }
                                ],
                            }
                        ],
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            research_tms.run(
                SimpleNamespace(
                    troubles_in=troubles_in,
                    wlc422_kq_u_dir=wlc422_dir,
                    uxlc_dir=uxlc_dir,
                    mam_simple_dir=mam_simple_dir,
                    out=out_path,
                )
            )

            payload = json.loads(out_path.read_text(encoding="utf-8"))
            row = payload["troublemakers"][0]

            self.assertEqual(row["diff_wlc_uxlc"], [])
            self.assertEqual(row["diff_wlc_mam"], [])

    def test_expand_subset_diff_to_wlc_focus_expands_single_dict_entry(self):
        out = research_tms._expand_subset_diff_to_wlc_focus(
            {"wlc422": "טוב֥ה", "uxlc": "טוֹבָה"},
            wlc_focus="יאב֥ד טוב֥ה",
            rhs_key="uxlc",
        )

        self.assertEqual(
            out,
            {
                "wlc422": "יאב֥ד טוב֥ה",
                "uxlc": "יאב֥ד טוֹבָה",
            },
        )

    def test_expand_subset_diff_to_wlc_focus_expands_list_entries(self):
        out = research_tms._expand_subset_diff_to_wlc_focus(
            [
                {"wlc422": "טוב֥ה", "mam_simple": "טוֹבָה"},
                {"wlc422": "יאב֥ד", "mam_simple": "יֹאבַד"},
            ],
            wlc_focus="יאב֥ד טוב֥ה",
            rhs_key="mam_simple",
        )

        self.assertEqual(
            out,
            [
                {"wlc422": "יאב֥ד טוב֥ה", "mam_simple": "יאב֥ד טוֹבָה"},
                {"wlc422": "יאב֥ד טוב֥ה", "mam_simple": "יֹאבַד טוב֥ה"},
            ],
        )

    def test_expand_subset_diff_to_wlc_focus_keeps_non_applicable_entries_unchanged(
        self,
    ):
        out_non_subset = research_tms._expand_subset_diff_to_wlc_focus(
            {"wlc422": "אחר", "uxlc": "אַחֵר"},
            wlc_focus="יאב֥ד טוב֥ה",
            rhs_key="uxlc",
        )
        out_note_only = research_tms._expand_subset_diff_to_wlc_focus(
            {"wlc_adds_notes": "]Q"},
            wlc_focus="יאב֥ד טוב֥ה",
            rhs_key="uxlc",
        )
        out_non_string_rhs = research_tms._expand_subset_diff_to_wlc_focus(
            {"wlc422": "טוב֥ה", "uxlc": {"text": "טוב֥ה", "note": "m"}},
            wlc_focus="יאב֥ד טוב֥ה",
            rhs_key="uxlc",
        )

        self.assertEqual(out_non_subset, {"wlc422": "אחר", "uxlc": "אַחֵר"})
        self.assertEqual(out_note_only, {"wlc_adds_notes": "]Q"})
        self.assertEqual(
            out_non_string_rhs,
            {"wlc422": "טוב֥ה", "uxlc": {"text": "טוב֥ה", "note": "m"}},
        )

    def test_expand_subset_diff_to_wlc_focus_uses_ec_9_18_fixture_focus(self):
        structured_text = research_tms.STRUCTURED_TEXT_BY_REF["ec 9:18"]
        focus = structured_text["wlc_focus"]

        self.assertEqual(focus, "יאב֥ד טוב֥ה")

        out = research_tms._expand_subset_diff_to_wlc_focus(
            {"wlc422": "טוב֥ה", "uxlc": "ט֖ובָה"},
            wlc_focus=focus,
            rhs_key="uxlc",
        )
        self.assertEqual(
            out,
            {
                "wlc422": "יאב֥ד טוב֥ה",
                "uxlc": "יאב֥ד ט֖ובָה",
            },
        )

    def test_structured_text_fixture_has_ob_1_1_summary(self):
        structured_text = research_tms.STRUCTURED_TEXT_BY_REF["ob 1:1"]
        self.assertEqual(
            structured_text.get("st-summary"),
            "Quirk in LC: עליה lacks an accent.",
        )

    def test_write_goerwitz_tms_html_report_renders_diff_and_assessment_labels(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            html_out = base / "gh-pages" / "accgram" / "goerwitz-tms.html"

            research_tms_report.write_goerwitz_tms_html_report(
                html_out,
                [
                    {
                        "ref": "gn 1:1",
                        "wlc422_kq_u_verse": {
                            "vels": [
                                "בראשית",
                                {"word": "אב", "notes": "]1"},
                                "אחרית",
                            ]
                        },
                        "diff_wlc_uxlc": {"wlc422": "אב", "uxlc": "אג"},
                        "diff_wlc_mam": [
                            {"wlc_adds_notes": "]1"},
                            {"wlc422": "אב", "mam_simple": "אב֙"},
                        ],
                        "structured_text": {
                            "wlc_focus": "אב",
                            "st-summary": "Link summary.",
                            "img": "LC-280B-col-3-line-2-Ezek-11v1.png",
                            "img_src_url": "https://manuscripts.sefaria.org/leningrad-color/BIB_LENCDX_F280B.jpg",
                            "assessment": {
                                "manuscript": "foo",
                                "bhs": "bar",
                                "wlc": "baz",
                                "uxlc": "qux",
                                "mam": "quux",
                            },
                            "uxlc_change": "https://tanach.us/Changes/2024.04.01%20-%20Changes/2024.04.01%20-%20Changes.xml?2023.09.16-12",
                            "uxlc_note_page": "https://tanach.us/Notes/Obadiah/Obadiah.1.1.17-c.html",
                            "comment": ["c1", "c2"],
                        },
                    }
                ],
            )

            self.assertTrue(html_out.exists())
            html_text = html_out.read_text(encoding="utf-8")
            html_text_compact = "".join(html_text.split())

            self.assertIn("<title>GoerwitzTMs</title>", html_text_compact)
            self.assertIn("<h1>GoerwitzTroublemakers</h1>", html_text_compact)
            self.assertNotIn("research-tms", html_text)
            self.assertIn('<h2id="tmgn1v1">gn1:1</h2>', html_text_compact)
            self.assertIn("diff_wlc_uxlc", html_text)
            self.assertIn("diff_wlc_mam[1]", html_text)
            self.assertIn("a.manuscript", html_text)
            self.assertIn("a.wlc", html_text)
            self.assertIn(
                "<td></td><td>foo</td><td>a.manuscript</td>",
                html_text,
            )
            self.assertNotIn("comment[1]", html_text)
            self.assertNotIn("comment[2]", html_text)
            self.assertIn('<pclass="goerwitz-tms-comment">c1</p>', html_text_compact)
            self.assertIn('<pclass="goerwitz-tms-comment">c2</p>', html_text_compact)
            self.assertIn("<h2>Subsets</h2>", html_text_compact)
            self.assertIn('href="goerwitz-tms-msp-y.html"', html_text_compact)
            self.assertIn('href="goerwitz-tms-msp-n.html"', html_text_compact)
            self.assertIn("<h2>WLCBracketNotes</h2>", html_text_compact)
            self.assertIn("<code>]1</code>", html_text_compact)
            self.assertIn('<td lang="hbo" dir="rtl">בראשית</td>', html_text)
            self.assertIn(
                '<td lang="hbo" dir="rtl">אב</td><td></td><td>wlc_focus.hbo</td>',
                html_text,
            )
            self.assertIn(
                '<td style="text-align: right;"><span title="BHS has been faithful to ל',
                html_text,
            )
            self.assertIn(
                "</span></td><td></td><td>wlc_focus.notes</td>",
                html_text,
            )
            self.assertIn('<td lang="hbo" dir="rtl">אחרית</td>', html_text)
            self.assertNotIn("bracket_notes", html_text)
            self.assertNotIn("אב: ]1", html_text)
            self.assertIn(
                'wlc_adds_notes: <span title="BHS has been faithful to ל',
                html_text,
            )
            self.assertNotIn("diff_wlc_uxlc.wlc_adds_notes", html_text)
            self.assertIn("Summary: Link summary.", html_text)
            self.assertIn("🔗</a>Summary:Linksummary.</p><p><a", html_text_compact)
            self.assertIn("UXLC change", html_text)
            self.assertIn("UXLC note page", html_text)
            self.assertIn('class="goerwitz-tms-image"', html_text)
            self.assertIn('class="goerwitz-tms-figure"', html_text)
            self.assertIn('class="goerwitz-tms-image-caption"', html_text)
            self.assertIn('src="../img/LC-280B-col-3-line-2-Ezek-11v1.png"', html_text)
            self.assertIn(
                '<figcaption class="goerwitz-tms-image-caption">Image source: <a href="https://manuscripts.sefaria.org/leningrad-color/BIB_LENCDX_F280B.jpg">280B</a> column 3 line 2</figcaption>',
                html_text,
            )
            self.assertIn(
                "https://manuscripts.sefaria.org/leningrad-color/BIB_LENCDX_F280B.jpg",
                html_text,
            )

    def test_write_goerwitz_tms_html_report_simplifies_matching_wlc_word_diff_pairs(
        self,
    ):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            html_out = base / "gh-pages" / "accgram" / "goerwitz-tms.html"

            research_tms_report.write_goerwitz_tms_html_report(
                html_out,
                [
                    {
                        "ref": "gn 1:1",
                        "wlc422_kq_u_verse": {"vels": ["לפני", "דבר", "אחרי"]},
                        "diff_wlc_uxlc": {"wlc422": "דבר", "uxlc": "דבר֙"},
                        "diff_wlc_mam": {"wlc422": "דבר", "mam_simple": "דבר֣"},
                        "structured_text": {
                            "wlc_focus": "דבר",
                        },
                    }
                ],
            )

            html_text = html_out.read_text(encoding="utf-8")
            self.assertIn(
                '<td lang="hbo" dir="rtl">דבר֙</td><td></td><td>diff_wlc_uxlc</td>',
                html_text,
            )
            self.assertIn(
                '<td lang="hbo" dir="rtl">דבר֣</td><td></td><td>diff_wlc_mam</td>',
                html_text,
            )
            self.assertNotIn("wlc422: דבר; uxlc: דבר֙", html_text)
            self.assertNotIn("wlc422: דבר; mam_simple: דבר֣", html_text)

    def test_write_goerwitz_tms_html_report_wraps_pointed_hebrew_in_comments(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            html_out = base / "gh-pages" / "accgram" / "goerwitz-tms.html"

            research_tms_report.write_goerwitz_tms_html_report(
                html_out,
                [
                    {
                        "ref": "gn 1:1",
                        "structured_text": {
                            "comment": "before אָב middle אב after",
                        },
                    }
                ],
            )

            html_text = html_out.read_text(encoding="utf-8")
            html_text_compact = "".join(html_text.split())

            self.assertIn(
                '<pclass="goerwitz-tms-comment">before<spanlang="hbo">אָב</span>middleאבafter</p>',
                html_text_compact,
            )
            self.assertNotIn('<spanlang="hbo">אב</span>', html_text_compact)

    def test_write_goerwitz_tms_html_report_suppresses_targeted_diff_row_for_1k_16_33(
        self,
    ):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            html_out = base / "gh-pages" / "accgram" / "goerwitz-tms.html"

            research_tms_report.write_goerwitz_tms_html_report(
                html_out,
                [
                    {
                        "ref": "1k 16:33",
                        "wlc422_kq_u_verse": {"vels": ["לפני", "מכ֨ל", "אחרי"]},
                        "diff_wlc_uxlc": [
                            {"wlc422": "אלה֣י", "uxlc": "אלהי"},
                            {"wlc422": "מכ֨ל", "uxlc": "מכל"},
                        ],
                    }
                ],
            )

            html_text = html_out.read_text(encoding="utf-8")
            self.assertNotIn("wlc422: אלה֣י; uxlc: אלהי", html_text)
            self.assertNotIn("diff_wlc_uxlc[1]", html_text)
            self.assertIn("wlc422: מכ֨ל; uxlc: מכל", html_text)
            self.assertIn("diff_wlc_uxlc[2]", html_text)

    def test_write_goerwitz_tms_html_report_renders_non_empty_multiword_wlc_focus_in_context(
        self,
    ):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            html_out = base / "gh-pages" / "accgram" / "goerwitz-tms.html"

            research_tms_report.write_goerwitz_tms_html_report(
                html_out,
                [
                    {
                        "ref": "ek 14:11",
                        "wlc422_kq_u_verse": {"vels": ["לפני", "וה֥יו", "ל֣י", "אחרי"]},
                        "structured_text": {
                            "wlc_focus": "וה֥יו ל֣י",
                        },
                    }
                ],
            )

            html_text_compact = "".join(html_out.read_text(encoding="utf-8").split())
            before_cell = '<tdlang="hbo"dir="rtl">לפני</td><td></td><td>wlc_before</td>'
            focus_cell = (
                '<tdlang="hbo"dir="rtl">וה֥יול֣י</td><td></td><td>wlc_focus</td>'
            )
            after_cell = '<tdlang="hbo"dir="rtl">אחרי</td><td></td><td>wlc_after</td>'

            self.assertIn(focus_cell, html_text_compact)
            self.assertNotIn("<td></td><td></td><td>wlc_focus</td>", html_text_compact)

            before_idx = html_text_compact.index(before_cell)
            focus_idx = html_text_compact.index(focus_cell)
            after_idx = html_text_compact.index(after_cell)
            self.assertLess(before_idx, focus_idx)
            self.assertLess(focus_idx, after_idx)

    def test_write_goerwitz_tms_html_report_splits_diff_wlc_uxlc_note_into_hbo_and_note_rows(
        self,
    ):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            html_out = base / "gh-pages" / "accgram" / "goerwitz-tms.html"

            research_tms_report.write_goerwitz_tms_html_report(
                html_out,
                [
                    {
                        "ref": "gn 1:1",
                        "wlc422_kq_u_verse": {"vels": ["לפני", "דבר", "אחרי"]},
                        "diff_wlc_uxlc": {
                            "wlc422": "דבר",
                            "uxlc": {"text": "דבר", "note": "m"},
                        },
                        "structured_text": {
                            "wlc_focus": "דבר",
                        },
                    }
                ],
            )

            html_text = html_out.read_text(encoding="utf-8")
            self.assertIn(
                '<td lang="hbo" dir="rtl">דבר</td><td></td><td>diff_wlc_uxlc.hbo</td>',
                html_text,
            )
            self.assertIn("<td>m</td><td></td><td>diff_wlc_uxlc.note</td>", html_text)
            self.assertNotIn(
                "<td>דבר (note: m)</td><td></td><td>diff_wlc_uxlc</td>", html_text
            )

    def test_write_goerwitz_tms_html_report_uses_phase3_url_conventions(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            html_out = base / "gh-pages" / "accgram" / "goerwitz-tms.html"

            research_tms_report.write_goerwitz_tms_html_report(
                html_out,
                [
                    {
                        "ref": "1k 6:2",
                        "wlc422_kq_u_verse": {"vels": ["foo"]},
                    },
                    {
                        "ref": "nu 25:19",
                        "wlc422_kq_u_verse": {"vels": ["bar"]},
                    },
                ],
            )

            html_text = html_out.read_text(encoding="utf-8")
            html_text_compact = "".join(html_text.split())
            self.assertIn(
                "https://bdenckla.github.io/MAM-with-doc/BC-1Kings.html#c6v2", html_text
            )
            self.assertIn("https://tanach.us/Tanach.xml?1Kings6:2", html_text)
            self.assertIn('<h2id="tm1k6v2">1k6:2</h2>', html_text_compact)
            self.assertIn('href="#tm1k6v2"', html_text)
            self.assertIn(
                "https://bdenckla.github.io/MAM-with-doc/A4-Numbers.html#c26v1",
                html_text,
            )
            self.assertIn("https://tanach.us/Tanach.xml?Num25:19", html_text)
            self.assertIn('<h2id="tmnu25v19">nu25:19</h2>', html_text_compact)
            self.assertIn('href="#tmnu25v19"', html_text)

    def test_write_goerwitz_tms_html_report_normalizes_mixed_token_payloads(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            html_out = base / "gh-pages" / "accgram" / "goerwitz-tms.html"

            research_tms_report.write_goerwitz_tms_html_report(
                html_out,
                [
                    {
                        "ref": "1k 1:1",
                        "wlc422_kq_u_verse": {
                            "vels": ["לפני", {"word": "דבר", "notes": "]Q]n"}, "אחרי"]
                        },
                        "diff_wlc_uxlc": {
                            "wlc422": {"word": "דבר", "notes": "]Q]n"},
                            "uxlc": {"text": "דבר", "note": "t"},
                        },
                        "diff_wlc_mam": {
                            "wlc422": ["אלף", {"text": "בית", "note": "x"}],
                            "mam_simple": ["אלף", "בית"],
                        },
                        "structured_text": {
                            "wlc_focus": "דבר",
                        },
                    }
                ],
            )

            html_text = html_out.read_text(encoding="utf-8")
            html_text_compact = "".join(html_text.split())
            self.assertNotIn("bracket_notes", html_text)
            self.assertIn("<h2>WLCBracketNotes</h2>", html_text_compact)
            self.assertIn("<code>]Q</code>", html_text_compact)
            self.assertIn("<code>]n</code>", html_text_compact)
            self.assertNotIn("<code>]1</code>", html_text_compact)
            self.assertIn(
                '<td lang="hbo" dir="rtl">דבר</td><td></td><td>wlc_focus.hbo</td>',
                html_text,
            )
            self.assertIn(
                '<td style="text-align: right;"><span title="Marks a place where we agree with BHQ against BHS in reading ל.',
                html_text,
            )
            self.assertIn(
                '>]Q</span><span title="An anomalous form in the text of ל.',
                html_text,
            )
            self.assertIn(
                "</span></td><td></td><td>wlc_focus.notes</td>",
                html_text,
            )
            self.assertIn(
                '<td lang="hbo" dir="rtl">דבר</td><td></td><td>diff_wlc_uxlc.hbo</td>',
                html_text,
            )
            self.assertIn("<td>t</td><td></td><td>diff_wlc_uxlc.note</td>", html_text)
            self.assertIn("wlc422: [אלף | בית (note: x)]", html_text)

    def test_write_goerwitz_tms_html_report_never_emits_bracket_notes_rows(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            html_out = base / "gh-pages" / "accgram" / "goerwitz-tms.html"

            research_tms_report.write_goerwitz_tms_html_report(
                html_out,
                [
                    {
                        "ref": "1k 1:1",
                        "wlc422_kq_u_verse": {
                            "vels": [
                                "לפני",
                                {"word": "דבר", "notes": "]Q"},
                                {"word": "אחר", "notes": "]N"},
                                "אחרי",
                            ]
                        },
                        "structured_text": {
                            "wlc_focus": "דבר",
                        },
                    }
                ],
            )

            html_text = html_out.read_text(encoding="utf-8")
            self.assertIn(
                '<td lang="hbo" dir="rtl">דבר</td><td></td><td>wlc_focus.hbo</td>',
                html_text,
            )
            self.assertIn(
                '<td style="text-align: right;"><span title="Marks a place where we agree with BHQ against BHS in reading ל.',
                html_text,
            )
            self.assertIn(
                "</span></td><td></td><td>wlc_focus.notes</td>",
                html_text,
            )
            self.assertNotIn("bracket_notes", html_text)
            self.assertIn("<code>]N</code>", "".join(html_text.split()))

    def test_subset_filters_use_silluq_no_sof_pasuq_marker(self):
        rows = [
            {
                "ref": "gn 1:1",
                "structured_text": {
                    "assessment": {
                        "wlc": "silluq-no_sof_pasuq?",
                    }
                },
            },
            {
                "ref": "gn 1:2",
                "structured_text": {
                    "assessment": {
                        "wlc": "etnahta",
                    }
                },
            },
        ]

        yes_rows = research_tms_report_subsets.filter_missing_sof_pasuq_yes_rows(rows)
        no_rows = research_tms_report_subsets.filter_missing_sof_pasuq_no_rows(rows)

        self.assertEqual([row["ref"] for row in yes_rows], ["gn 1:1"])
        self.assertEqual([row["ref"] for row in no_rows], ["gn 1:2"])

    def test_write_goerwitz_tms_msp_yes_html_report_includes_only_yes_rows_and_related_links(
        self,
    ):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            main_html_out = base / "gh-pages" / "accgram" / "goerwitz-tms.html"

            rows = [
                {
                    "ref": "gn 1:1",
                    "wlc422_kq_u_verse": {"vels": ["א"]},
                    "structured_text": {"assessment": {"wlc": "silluq-no_sof_pasuq"}},
                },
                {
                    "ref": "gn 1:2",
                    "wlc422_kq_u_verse": {"vels": ["ב"]},
                    "structured_text": {"assessment": {"wlc": "etnahta"}},
                },
            ]

            research_tms_report.write_goerwitz_tms_msp_yes_html_report(
                main_html_out, rows
            )

            yes_html_out = main_html_out.parent / "goerwitz-tms-msp-y.html"
            self.assertTrue(yes_html_out.exists())
            html_text = yes_html_out.read_text(encoding="utf-8")
            html_text_compact = "".join(html_text.split())

            self.assertIn("<title>GoerwitzTMs(msp-y)</title>", html_text_compact)
            self.assertIn("<h1>GoerwitzTroublemakers(msp-y)</h1>", html_text_compact)
            self.assertNotIn("research-tms", html_text)
            self.assertIn('<h2id="tmgn1v1">gn1:1</h2>', html_text_compact)
            self.assertNotIn('<h2id="tmgn1v2">gn1:2</h2>', html_text_compact)
            self.assertIn("<h2>Relatedpages</h2>", html_text_compact)
            self.assertIn('href="goerwitz-tms.html">mainpage</a>', html_text_compact)
            self.assertIn(
                'href="goerwitz-tms-msp-n.html">missingsofpasuq:no</a>',
                html_text_compact,
            )

    def test_write_goerwitz_tms_msp_no_html_report_includes_only_no_rows_and_related_links(
        self,
    ):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            main_html_out = base / "gh-pages" / "accgram" / "goerwitz-tms.html"

            rows = [
                {
                    "ref": "gn 1:1",
                    "wlc422_kq_u_verse": {"vels": ["א"]},
                    "structured_text": {"assessment": {"wlc": "silluq-no_sof_pasuq?"}},
                },
                {
                    "ref": "gn 1:2",
                    "wlc422_kq_u_verse": {"vels": ["ב"]},
                    "structured_text": {"assessment": {"wlc": "etnahta"}},
                },
            ]

            research_tms_report.write_goerwitz_tms_msp_no_html_report(
                main_html_out, rows
            )

            no_html_out = main_html_out.parent / "goerwitz-tms-msp-n.html"
            self.assertTrue(no_html_out.exists())
            html_text = no_html_out.read_text(encoding="utf-8")
            html_text_compact = "".join(html_text.split())

            self.assertIn("<title>GoerwitzTMs(msp-n)</title>", html_text_compact)
            self.assertIn("<h1>GoerwitzTroublemakers(msp-n)</h1>", html_text_compact)
            self.assertNotIn("research-tms", html_text)
            self.assertNotIn('<h2id="tmgn1v1">gn1:1</h2>', html_text_compact)
            self.assertIn('<h2id="tmgn1v2">gn1:2</h2>', html_text_compact)
            self.assertIn("<h2>Relatedpages</h2>", html_text_compact)
            self.assertIn('href="goerwitz-tms.html">mainpage</a>', html_text_compact)
            self.assertIn(
                'href="goerwitz-tms-msp-y.html">missingsofpasuq:yes</a>',
                html_text_compact,
            )

    def test_run_missing_mam_simple_raises_fail_fast(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            mam_simple_dir = base / "mam-simple"
            out_path = base / "out" / "research-troublemakers.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps(
                    {
                        "troublemakers": [
                            {
                                "ref": "gn 1:2",
                                "content": "payload-2",
                            }
                        ]
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text(
                json.dumps(
                    [
                        {
                            "bcv": "gn1:2",
                            "vels": ["וְהָאָ֗רֶץ"],
                        }
                    ],
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (uxlc_dir / "Genesis.xml").write_text(
                """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Tanach>
  <c n=\"1\">
    <v n=\"2\">
      <w>וְהָאָ֗רֶץ</w>
    </v>
  </c>
</Tanach>
""",
                encoding="utf-8",
            )
            (mam_simple_dir / "Gen.json").write_text(
                json.dumps(
                    {"versification-tradition": "vtbhs", "contents": []},
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            with self.assertRaisesRegex(
                ValueError, r"Missing MAM-simple verse for gn 1:2"
            ):
                research_tms.run(
                    SimpleNamespace(
                        troubles_in=troubles_in,
                        wlc422_kq_u_dir=wlc422_dir,
                        uxlc_dir=uxlc_dir,
                        mam_simple_dir=mam_simple_dir,
                        out=out_path,
                    )
                )

            self.assertFalse(out_path.exists())

    def test_run_missing_wlc422_raises_fail_fast(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            mam_simple_dir = base / "mam-simple"
            out_path = base / "out" / "research-troublemakers.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps(
                    {
                        "troublemakers": [
                            {
                                "ref": "gn 1:2",
                                "content": "payload-2",
                            }
                        ]
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text("[]\n", encoding="utf-8")
            (uxlc_dir / "Genesis.xml").write_text(
                """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Tanach>
  <c n=\"1\">
    <v n=\"2\">
      <w>וְהָאָ֗רֶץ</w>
    </v>
  </c>
</Tanach>
""",
                encoding="utf-8",
            )
            (mam_simple_dir / "Gen.json").write_text(
                json.dumps(
                    {
                        "versification-tradition": "vtbhs",
                        "contents": [
                            {
                                "type": "book39",
                                "osisID": "Gen",
                                "contents": [
                                    {
                                        "type": "chapter",
                                        "osisID": "Gen.1",
                                        "contents": [
                                            {
                                                "type": "verse",
                                                "osisID": "Gen.1.2",
                                                "contents": [
                                                    {
                                                        "type": "text",
                                                        "text": "וְהָאָ֗רֶץ",
                                                    }
                                                ],
                                            }
                                        ],
                                    }
                                ],
                            }
                        ],
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            with self.assertRaisesRegex(
                ValueError, r"Missing wlc422-kq-u verse for gn 1:2"
            ):
                research_tms.run(
                    SimpleNamespace(
                        troubles_in=troubles_in,
                        wlc422_kq_u_dir=wlc422_dir,
                        uxlc_dir=uxlc_dir,
                        mam_simple_dir=mam_simple_dir,
                        out=out_path,
                    )
                )

            self.assertFalse(out_path.exists())

    def test_run_missing_uxlc_raises_fail_fast(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            mam_simple_dir = base / "mam-simple"
            out_path = base / "out" / "research-troublemakers.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps(
                    {
                        "troublemakers": [
                            {
                                "ref": "gn 1:2",
                                "content": "payload-2",
                            }
                        ]
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text(
                json.dumps(
                    [
                        {
                            "bcv": "gn1:2",
                            "vels": ["וְהָאָ֗רֶץ"],
                        }
                    ],
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (uxlc_dir / "Genesis.xml").write_text(
                """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Tanach>
  <c n=\"1\">
    <v n=\"1\">
      <w>בְּרֵאשִׁ֖ית</w>
    </v>
  </c>
</Tanach>
""",
                encoding="utf-8",
            )
            (mam_simple_dir / "Gen.json").write_text(
                json.dumps(
                    {
                        "versification-tradition": "vtbhs",
                        "contents": [
                            {
                                "type": "book39",
                                "osisID": "Gen",
                                "contents": [
                                    {
                                        "type": "chapter",
                                        "osisID": "Gen.1",
                                        "contents": [
                                            {
                                                "type": "verse",
                                                "osisID": "Gen.1.2",
                                                "contents": [
                                                    {
                                                        "type": "text",
                                                        "text": "וְהָאָ֗רֶץ",
                                                    }
                                                ],
                                            }
                                        ],
                                    }
                                ],
                            }
                        ],
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            with self.assertRaisesRegex(ValueError, r"Missing UXLC verse for gn 1:2"):
                research_tms.run(
                    SimpleNamespace(
                        troubles_in=troubles_in,
                        wlc422_kq_u_dir=wlc422_dir,
                        uxlc_dir=uxlc_dir,
                        mam_simple_dir=mam_simple_dir,
                        out=out_path,
                    )
                )

            self.assertFalse(out_path.exists())

    def test_run_creates_output_path_and_writes_expected_top_level_fields(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            mam_simple_dir = base / "mam-simple"
            out_path = base / "nested" / "deep" / "research-troublemakers.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps({"troublemakers": []}, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text("[]\n", encoding="utf-8")
            (mam_simple_dir / "Gen.json").write_text(
                json.dumps(
                    {"versification-tradition": "vtbhs", "contents": []},
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            research_tms.run(
                SimpleNamespace(
                    troubles_in=troubles_in,
                    wlc422_kq_u_dir=wlc422_dir,
                    uxlc_dir=uxlc_dir,
                    mam_simple_dir=mam_simple_dir,
                    out=out_path,
                )
            )

            self.assertTrue(out_path.exists())
            payload = json.loads(out_path.read_text(encoding="utf-8"))
            self.assertIn("provenance", payload)
            self.assertIn("summary", payload)
            self.assertIn("troublemakers", payload)
            self.assertEqual(payload["summary"]["troublemakers"], 0)

    def test_run_derives_default_html_out_from_out_context_when_missing_on_namespace(
        self,
    ):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            mam_simple_dir = base / "mam-simple"
            out_path = base / "out" / "research-troublemakers.json"
            expected_html_out = base / "gh-pages" / "accgram" / "goerwitz-tms.html"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps({"troublemakers": []}, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text("[]\n", encoding="utf-8")
            (mam_simple_dir / "Gen.json").write_text(
                json.dumps(
                    {"versification-tradition": "vtbhs", "contents": []},
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            research_tms.run(
                SimpleNamespace(
                    troubles_in=troubles_in,
                    wlc422_kq_u_dir=wlc422_dir,
                    uxlc_dir=uxlc_dir,
                    mam_simple_dir=mam_simple_dir,
                    out=out_path,
                )
            )

            self.assertTrue(out_path.exists())
            self.assertTrue(expected_html_out.exists())

    def test_run_respects_explicit_html_out_override(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            mam_simple_dir = base / "mam-simple"
            out_path = base / "out" / "research-troublemakers.json"
            html_out = base / "custom" / "goerwitz-tms-phase1.html"
            default_html_out = base / "gh-pages" / "accgram" / "goerwitz-tms.html"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps({"troublemakers": []}, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text("[]\n", encoding="utf-8")
            (mam_simple_dir / "Gen.json").write_text(
                json.dumps(
                    {"versification-tradition": "vtbhs", "contents": []},
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            research_tms.run(
                SimpleNamespace(
                    troubles_in=troubles_in,
                    wlc422_kq_u_dir=wlc422_dir,
                    uxlc_dir=uxlc_dir,
                    mam_simple_dir=mam_simple_dir,
                    out=out_path,
                    html_out=html_out,
                )
            )

            self.assertTrue(out_path.exists())
            self.assertTrue(html_out.exists())
            self.assertFalse(default_html_out.exists())

    def test_run_fails_fast_on_html_write_error_after_json_write_attempt(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            mam_simple_dir = base / "mam-simple"
            out_path = base / "out" / "research-troublemakers.json"

            non_dir_parent = base / "not-a-dir"
            non_dir_parent.write_text("occupied", encoding="utf-8")
            bad_html_out = non_dir_parent / "goerwitz-tms.html"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps({"troublemakers": []}, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text("[]\n", encoding="utf-8")
            (mam_simple_dir / "Gen.json").write_text(
                json.dumps(
                    {"versification-tradition": "vtbhs", "contents": []},
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            with self.assertRaises(FileExistsError):
                research_tms.run(
                    SimpleNamespace(
                        troubles_in=troubles_in,
                        wlc422_kq_u_dir=wlc422_dir,
                        uxlc_dir=uxlc_dir,
                        mam_simple_dir=mam_simple_dir,
                        out=out_path,
                        html_out=bad_html_out,
                    )
                )

            self.assertTrue(out_path.exists())

    def test_structured_text_sanity_allows_book_name_and_word_number_mismatch_forms(
        self,
    ):
        with TemporaryDirectory() as tmp_dir:
            all_changes_path = Path(tmp_dir) / "all_changes.json"
            all_changes_path.write_text(
                json.dumps(
                    [
                        {
                            "release": "2023.04.01",
                            "changeset": "2022.12.10",
                            "n": 16,
                            "citation": "Jer 9:11.19",
                            "changetext": "מבל֖י",
                        }
                    ],
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            troublemaker_structured_text_sanity.sanity_check_structured_text(
                refs=["je 9:11"],
                structured_text_by_ref={
                    "je 9:11": {
                        "uxlc_change": (
                            "https://tanach.us/Changes/2023.04.01%20-%20Changes/"
                            "2023.04.01%20-%20Changes.xml?2022.12.10-16"
                        ),
                        "assessment": {"uxlc": "מבל֖י"},
                    }
                },
                all_changes_path=all_changes_path,
            )

    def test_structured_text_sanity_rejects_citation_ref_mismatch(self):
        with TemporaryDirectory() as tmp_dir:
            all_changes_path = Path(tmp_dir) / "all_changes.json"
            all_changes_path.write_text(
                json.dumps(
                    [
                        {
                            "release": "2023.04.01",
                            "changeset": "2022.12.10",
                            "n": 16,
                            "citation": "Jer 9:10.19",
                            "changetext": "מבל֖י",
                        }
                    ],
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            with self.assertRaisesRegex(ValueError, r"citation/ref mismatch"):
                troublemaker_structured_text_sanity.sanity_check_structured_text(
                    refs=["je 9:11"],
                    structured_text_by_ref={
                        "je 9:11": {
                            "uxlc_change": (
                                "https://tanach.us/Changes/2023.04.01%20-%20Changes/"
                                "2023.04.01%20-%20Changes.xml?2022.12.10-16"
                            ),
                            "assessment": {"uxlc": "מבל֖י"},
                        }
                    },
                    all_changes_path=all_changes_path,
                )

    def test_structured_text_sanitize_word_drops_non_target_marks(self):
        actual = troublemaker_structured_text_sanity.sanitize_word_for_change_match(
            "מְב\u05bdל֖י "
        )
        expected = troublemaker_structured_text_sanity.sanitize_word_for_change_match(
            "מבל֖י"
        )
        self.assertEqual(actual, expected)

    def test_diff_uxlc_matches_changetext_true_after_sanitization(self):
        matches = troublemaker_structured_text_sanity.diff_uxlc_matches_changetext(
            diff_wlc_uxlc={"wlc422": "ועשר֤ים", "uxlc": "וְעֶשְׂרִ֣ים"},
            changetext="ועשר֣ים",
        )
        self.assertTrue(matches)

    def test_diff_uxlc_matches_changetext_false_when_different(self):
        matches = troublemaker_structured_text_sanity.diff_uxlc_matches_changetext(
            diff_wlc_uxlc={"wlc422": "ועשר֤ים", "uxlc": "ועשר֣ים"},
            changetext="ועשרים",
        )
        self.assertFalse(matches)

    def test_diff_uxlc_matches_changetext_raises_on_non_hebrew_text(self):
        with self.assertRaisesRegex(ValueError, r"Expected Hebrew-script text"):
            troublemaker_structured_text_sanity.diff_uxlc_matches_changetext(
                diff_wlc_uxlc={"wlc422": "ועשר֤ים", "uxlc": "munax"},
                changetext="ועשר֣ים",
            )

    def test_descriptor_from_hebrew_token_tevir(self):
        descriptor = troublemaker_structured_text_sanity.descriptor_from_hebrew_token(
            "אש֛ר"
        )
        self.assertEqual(descriptor, "tevir")

    def test_descriptor_from_hebrew_token_etnaxta(self):
        descriptor = troublemaker_structured_text_sanity.descriptor_from_hebrew_token(
            "שנ֑ים"
        )
        self.assertEqual(descriptor, "etnaxta")

    def test_descriptor_from_hebrew_token_pashta_on_letter(self):
        descriptor = troublemaker_structured_text_sanity.descriptor_from_hebrew_token(
            "שנה֙"
        )
        self.assertEqual(descriptor, "pashta on he")

    def test_descriptor_from_hebrew_token_no_accent(self):
        self.assertEqual(
            troublemaker_structured_text_sanity.descriptor_from_hebrew_token("מבלי"),
            "no_accent",
        )
        self.assertEqual(
            troublemaker_structured_text_sanity.descriptor_from_hebrew_token("עליה"),
            "no_accent",
        )

    def test_descriptor_from_hebrew_token_maqaf(self):
        descriptor = troublemaker_structured_text_sanity.descriptor_from_hebrew_token(
            "נכח־"
        )
        self.assertEqual(descriptor, "maqaf")

    def test_descriptor_from_hebrew_token_two_over_accents(self):
        descriptor = troublemaker_structured_text_sanity.descriptor_from_hebrew_token(
            "אריצ֨נו֙"
        )
        self.assertEqual(descriptor, "qadma on tsadi, pashta on vav")

    def test_descriptor_from_hebrew_token_returns_none_for_allowlisted_exceptions(self):
        self.assertIsNone(
            troublemaker_structured_text_sanity.descriptor_from_hebrew_token("טוב֖ה")
        )
        self.assertIsNone(
            troublemaker_structured_text_sanity.descriptor_from_hebrew_token("ישראל֘")
        )

    def test_descriptor_from_hebrew_token_asserts_for_unmapped_non_allowlisted_token(
        self,
    ):
        with self.assertRaisesRegex(
            AssertionError,
            r"No descriptor for accent token unless explicitly allowlisted",
        ):
            troublemaker_structured_text_sanity.descriptor_from_hebrew_token("אב֚")

    def test_descriptor_from_hebrew_token_asserts_on_over_accent_without_letter(self):
        with self.assertRaisesRegex(
            AssertionError, r"Over-accent must follow a Hebrew letter"
        ):
            troublemaker_structured_text_sanity.descriptor_from_hebrew_token("֙")

    def test_assessment_uxlc_matches_converted_diff_uxlc_true(self):
        matches = troublemaker_structured_text_sanity.assessment_uxlc_matches_converted_diff_uxlc(
            assessment_uxlc="tevir",
            diff_wlc_uxlc={"wlc422": "אש֥ר", "uxlc": "אש֛ר"},
        )
        self.assertTrue(matches)

    def test_assessment_uxlc_matches_converted_diff_uxlc_maqaf_alias(self):
        matches = troublemaker_structured_text_sanity.assessment_uxlc_matches_converted_diff_uxlc(
            assessment_uxlc="meteg-maqaf",
            diff_wlc_uxlc={"wlc422": "נ֥כח", "uxlc": "נכח־"},
        )
        self.assertTrue(matches)

    def test_assessment_uxlc_matches_converted_diff_uxlc_maqaf_exact(self):
        matches = troublemaker_structured_text_sanity.assessment_uxlc_matches_converted_diff_uxlc(
            assessment_uxlc="maqaf",
            diff_wlc_uxlc={"wlc422": "נ֥כח", "uxlc": "נכח־"},
        )
        self.assertTrue(matches)

    def test_assessment_uxlc_matches_converted_diff_uxlc_hebrew_letter_suffix(self):
        matches = troublemaker_structured_text_sanity.assessment_uxlc_matches_converted_diff_uxlc(
            assessment_uxlc="pashta on ה",
            diff_wlc_uxlc={"wlc422": "שנ֨ה", "uxlc": "שנה֙"},
        )
        self.assertTrue(matches)

    def test_structured_text_sanity_does_not_compare_assessment_uxlc_to_changetext(
        self,
    ):
        with TemporaryDirectory() as tmp_dir:
            all_changes_path = Path(tmp_dir) / "all_changes.json"
            all_changes_path.write_text(
                json.dumps(
                    [
                        {
                            "release": "2022.12.07",
                            "changeset": "2022.08.31",
                            "n": 9,
                            "citation": "1Kings 6:2.17",
                            "changetext": "וְעֶשְׂרִ֣ים",
                        }
                    ],
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            troublemaker_structured_text_sanity.sanity_check_structured_text(
                refs=["1k 6:2"],
                structured_text_by_ref={
                    "1k 6:2": {
                        "uxlc_change": (
                            "https://tanach.us/Changes/2022.12.07%20-%20Changes/"
                            "2022.12.07%20-%20Changes.xml?2022.08.31-9"
                        ),
                        "assessment": {"uxlc": "munax"},
                        "wlc_focus": "ועשר֤ים",
                    }
                },
                all_changes_path=all_changes_path,
            )

    def test_load_all_changes_by_url_indexes_rows(self):
        with TemporaryDirectory() as tmp_dir:
            all_changes_path = Path(tmp_dir) / "all_changes.json"
            all_changes_path.write_text(
                json.dumps(
                    [
                        {
                            "release": "2022.12.07",
                            "changeset": "2022.08.31",
                            "n": 9,
                            "citation": "1Kings 6:2.17",
                            "changetext": "וְעֶשְׂרִ֣ים",
                        }
                    ],
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            by_url = troublemaker_structured_text_sanity.load_all_changes_by_url(
                all_changes_path
            )
            self.assertIn(
                "https://tanach.us/Changes/2022.12.07%20-%20Changes/2022.12.07%20-%20Changes.xml?2022.08.31-9",
                by_url,
            )


if __name__ == "__main__":
    unittest.main()
