"""Tests for the wlc-utils provenance wrapper (issue #34).

The wrapper binds this repo's logical name (repo_paths.REPO_NAME) so breadcrumbs
read "wlc-utils/..." regardless of the checkout directory name -- even a git
worktree.  The repo-agnostic override mechanism itself is unit-tested upstream in
MAM-basics' test_mb_cmn_provenance.
"""

from __future__ import annotations

import repo_paths
import wlc_provenance


def test_wrapper_supplies_repo_name() -> None:
    assert repo_paths.REPO_NAME == "wlc-utils"
    generator = repo_paths.repo_root() / "py" / "main_accgram.py"
    assert (
        "wlc-utils/py/main_accgram.py"
        in wlc_provenance.generated_by_text(str(generator))
    )


def test_wrapper_html_comment_and_json_use_repo_name() -> None:
    generator = repo_paths.repo_root() / "py" / "main_accgram.py"
    assert "wlc-utils/py/main_accgram.py" in wlc_provenance.generated_html_comment(
        str(generator)
    )
    payload = wlc_provenance.with_json_provenance({"x": 1}, str(generator))
    assert payload["provenance"].startswith("This file was generated by wlc-utils/")
    assert payload["x"] == 1
