# Initially generated by GitHub Copilot.

from __future__ import annotations

import json
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path
from tempfile import TemporaryDirectory
from types import SimpleNamespace

from accgram.hebrew_verse_sanitize import sanitize_verse_text_payload
from accgram import mam_simple_diff
from accgram import mam_simple_verse
from accgram import research_troublemakers
from accgram import verse_json_smart_concat
from accgram import wlc_uxlc_diff


class TestAccgramResearchTroublemakers(unittest.TestCase):
    def test_smart_concatenate_string_runs_joins_with_space_without_maqaf(self):
        out = verse_json_smart_concat.smart_concatenate_string_runs(["אב", "גד", {"x": 1}, "דה", "וז"])

        self.assertEqual(out, ["אב גד", {"x": 1}, "דה וז"])

    def test_smart_concatenate_string_runs_joins_without_space_after_maqaf(self):
        out = verse_json_smart_concat.smart_concatenate_string_runs(["אב־", "גד", "דה"])

        self.assertEqual(out, ["אב־גד דה"])

    def test_smart_concatenate_string_runs_allows_multi_token_run(self):
        out = verse_json_smart_concat.smart_concatenate_string_runs(["אב", "גד", "דה"])

        self.assertEqual(out, ["אב גד דה"])

    def test_smart_concatenate_string_runs_attaches_paseq_to_previous_word(self):
        out = verse_json_smart_concat.smart_concatenate_string_runs(["אב", "׀", "גד"])

        self.assertEqual(out, ["אב׀ גד"])

    def test_smart_concatenate_string_runs_asserts_on_preexisting_space(self):
        with self.assertRaises(AssertionError):
            verse_json_smart_concat.smart_concatenate_string_runs(["אב ג", "דה"])

    def test_smart_concatenate_row_for_json_does_not_touch_diff(self):
        row = {
            "wlc422_kq_u_verse": {"vels": ["אב", "גד"]},
            "uxlc_verse": ["אב", "גד"],
            "diff_wlc_uxlc": [{"wlc422": ["אב"], "uxlc": ["אג"]}],
            "mam_simple_verse": {"vels": ["אב", "גד"]},
            "diff_wlc_mam": [{"wlc422": ["אב"], "mam_simple": ["אג"]}],
        }

        out = verse_json_smart_concat.smart_concatenate_row_for_json(row)

        self.assertEqual(out["wlc422_kq_u_verse"], {"vels": ["אב גד"]})
        self.assertEqual(out["uxlc_verse"], ["אב גד"])
        self.assertEqual(out["diff_wlc_uxlc"], row["diff_wlc_uxlc"])
        self.assertEqual(out["mam_simple_verse"], {"vels": ["אב גד"]})
        self.assertEqual(out["diff_wlc_mam"], row["diff_wlc_mam"])

    def test_load_mam_simple_for_refs_and_diff_wlc_mam(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            mam_simple_dir = base / "mam-simple"
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            (mam_simple_dir / "Gen.json").write_text(
                json.dumps(
                    {
                        "versification-tradition": "vtbhs",
                        "contents": [
                            {
                                "type": "book39",
                                "osisID": "Gen",
                                "contents": [
                                    {
                                        "type": "chapter",
                                        "osisID": "Gen.1",
                                        "contents": [
                                            {
                                                "type": "verse",
                                                "osisID": "Gen.1.1",
                                                "contents": [
                                                    {"type": "text", "text": "אב־"},
                                                    {"type": "text", "text": "גד"},
                                                    {"type": "lp-paseq"},
                                                    {
                                                        "type": "kq",
                                                        "contents": [
                                                            {
                                                                "type": "kq-k",
                                                                "contents": [
                                                                    {"type": "text", "text": "כתיב"}
                                                                ],
                                                            },
                                                            {
                                                                "type": "kq-q",
                                                                "contents": [
                                                                    {"type": "text", "text": "קְרֵי"}
                                                                ],
                                                            },
                                                        ],
                                                    },
                                                    {"type": "text", "text": " דה־ו"},
                                                ],
                                            }
                                        ],
                                    }
                                ],
                            }
                        ],
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            loaded = mam_simple_verse.load_mam_simple_for_refs(mam_simple_dir, {"gn": {(1, 1)}})

            self.assertIn("gn1:1", loaded)
            self.assertEqual(
                loaded["gn1:1"]["mam_simple_verse"]["vels"],
                ["אב־", "גד", "׀", "קְרֵי", "דה־", "ו"],
            )

            diff = mam_simple_diff.diff_wlc_mam(
                {"vels": ["אב־", "גד", "קְרֵי", "דה־ו"]},
                loaded["gn1:1"]["mam_simple_verse"],
            )

            self.assertIsInstance(diff, list)
            self.assertGreaterEqual(len(diff), 1)
            self.assertIn("mam_simple", diff[0])

    def test_diff_wlc_uxlc_simplifies_uxlc_note_only_delta(self):
        diff = wlc_uxlc_diff.diff_wlc_uxlc(
            {"vels": ["foo"]},
            [{"text": "foo", "note": "bar"}],
        )

        self.assertEqual(diff, [{"uxlc_adds_note": "bar"}])

    def test_diff_wlc_uxlc_simplifies_note_only_delta(self):
        diff = wlc_uxlc_diff.diff_wlc_uxlc(
            {"vels": [{"word": "foo", "notes": ["]Q", "]n", "]p"]}]},
            ["foo"],
        )

        self.assertEqual(diff, [{"wlc_adds_notes": ["]Q", "]n", "]p"]}])

    def test_diff_wlc_uxlc_reports_token_changes(self):
        diff = wlc_uxlc_diff.diff_wlc_uxlc(
            {"vels": ["a", "b", "c"]},
            ["a", "x", "c"],
        )

        self.assertEqual(diff, [{"wlc422": ["b"], "uxlc": ["x"]}])

    def test_diff_wlc_mam_normalizes_standalone_paseq_tokenization(self):
        diff = mam_simple_diff.diff_wlc_mam(
            {"vels": ["אב׀", "גד"]},
            {"vels": ["אב", "׀", "גד"]},
        )

        self.assertEqual(diff, [])

    def test_to_xmlish_word_preserves_text_after_inline_x_child(self):
        element = ET.fromstring("<w>פֶ֛<x>t</x>לִאי׃</w>")

        node = research_troublemakers._to_xmlish_verse_child(element)
        node = sanitize_verse_text_payload(node)

        self.assertIsInstance(node, dict)
        self.assertEqual(node, {"text": "פ֛לאי׃", "note": "t"})

    def test_sanitize_keeps_only_last_meteg_in_last_word(self):
        wlc422_verse = {
            "bcv": "gn1:1",
            "vels": ["אֽב", "גֽדֽה"],
        }
        uxlc_nodes = ["אֽב", "גֽדֽה"]

        wlc_clean = sanitize_verse_text_payload(wlc422_verse)
        uxlc_clean = sanitize_verse_text_payload(uxlc_nodes)

        self.assertEqual(wlc_clean["vels"], ["אב", "גדֽה"])
        self.assertEqual(uxlc_clean, ["אב", "גדֽה"])

    def test_run_happy_path_enriches_both_sources(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            mam_simple_dir = base / "mam-simple"
            out_path = base / "out" / "research-troublemakers.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps(
                    {
                        "troublemakers": [
                            {
                                "ref": "gn 1:1",
                                "content": "payload",
                            }
                        ]
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text(
                json.dumps(
                    [
                        {
                            "bcv": "gn1:1",
                            "vels": ["בְּרֵאשִׁ֖ית", {"sam_pe_inun": "P"}, "בָּרָ֣א"],
                        }
                    ],
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (uxlc_dir / "Genesis.xml").write_text(
                """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Tanach>
  <c n=\"1\">
    <v n=\"1\">
      <w>בְּרֵאשִׁ֖ית<s t=\"large\">ע</s><x>5</x></w>
      <k>כתיב</k>
      <q>קְרֵי</q>
      <samekh/>
    </v>
  </c>
</Tanach>
""",
                encoding="utf-8",
            )
            (mam_simple_dir / "Gen.json").write_text(
                json.dumps(
                    {
                        "versification-tradition": "vtbhs",
                        "contents": [
                            {
                                "type": "book39",
                                "osisID": "Gen",
                                "contents": [
                                    {
                                        "type": "chapter",
                                        "osisID": "Gen.1",
                                        "contents": [
                                            {
                                                "type": "verse",
                                                "osisID": "Gen.1.1",
                                                "contents": [
                                                    {"type": "text", "text": "אב־"},
                                                    {"type": "text", "text": "גד"},
                                                    {"type": "lp-paseq"},
                                                    {
                                                        "type": "kq",
                                                        "contents": [
                                                            {
                                                                "type": "kq-k",
                                                                "contents": [
                                                                    {"type": "text", "text": "כתיב"}
                                                                ],
                                                            },
                                                            {
                                                                "type": "kq-q",
                                                                "contents": [
                                                                    {"type": "text", "text": "קְרֵי"}
                                                                ],
                                                            },
                                                        ],
                                                    },
                                                    {"type": "text", "text": " דה־ו"},
                                                ],
                                            }
                                        ],
                                    }
                                ],
                            }
                        ],
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            research_troublemakers.run(
                SimpleNamespace(
                    troubles_in=troubles_in,
                    wlc422_kq_u_dir=wlc422_dir,
                    uxlc_dir=uxlc_dir,
                    mam_simple_dir=mam_simple_dir,
                    out=out_path,
                )
            )

            self.assertTrue(out_path.exists())
            payload = json.loads(out_path.read_text(encoding="utf-8"))
            self.assertEqual(
                payload["provenance"],
                "This file was generated by wlc-utils/py/accgram/research_troublemakers.py.",
            )
            self.assertEqual(payload["summary"]["troublemakers"], 1)

            row = payload["troublemakers"][0]
            self.assertEqual(row["ref"], "gn 1:1")
            self.assertEqual(row["wlc422_kq_u_verse"]["vels"][0], "בראש֖ית בר֣א")
            self.assertIsInstance(row["diff_wlc_uxlc"], list)
            self.assertGreaterEqual(len(row["diff_wlc_uxlc"]), 1)
            self.assertFalse(
                any(
                    isinstance(token, dict) and set(token.keys()) == {"sam_pe_inun"}
                    for token in row["wlc422_kq_u_verse"]["vels"]
                )
            )

            xmlish = row["uxlc_verse"]
            self.assertEqual(xmlish[0]["tag"], "w")
            self.assertEqual(xmlish[0]["text"], "בראש֖ית")
            self.assertEqual(xmlish[1], "קרי")
            self.assertFalse(
                any(
                    isinstance(node, dict) and node.get("tag") in {"pe", "samekh"}
                    for node in xmlish
                )
            )
            self.assertEqual(xmlish[0]["children"][0]["tag"], "s")
            self.assertEqual(xmlish[0]["children"][0]["attrs"]["t"], "large")
            self.assertEqual(xmlish[0]["children"][1]["tag"], "x")
            self.assertEqual(xmlish[0]["children"][1]["text"], "5")

            self.assertEqual(row["mam_simple_verse"]["vels"], ["אב־גד׀ קרי דה־ו"])
            self.assertIsInstance(row["diff_wlc_mam"], list)
            self.assertGreaterEqual(len(row["diff_wlc_mam"]), 1)
            self.assertIn("mam_simple", row["diff_wlc_mam"][0])

    def test_run_missing_mam_simple_raises_fail_fast(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            mam_simple_dir = base / "mam-simple"
            out_path = base / "out" / "research-troublemakers.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps(
                    {
                        "troublemakers": [
                            {
                                "ref": "gn 1:2",
                                "content": "payload-2",
                            }
                        ]
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text(
                json.dumps(
                    [
                        {
                            "bcv": "gn1:2",
                            "vels": ["וְהָאָ֗רֶץ"],
                        }
                    ],
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (uxlc_dir / "Genesis.xml").write_text(
                """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Tanach>
  <c n=\"1\">
    <v n=\"2\">
      <w>וְהָאָ֗רֶץ</w>
    </v>
  </c>
</Tanach>
""",
                encoding="utf-8",
            )
            (mam_simple_dir / "Gen.json").write_text(
                json.dumps({"versification-tradition": "vtbhs", "contents": []}, ensure_ascii=False, indent=2)
                + "\n",
                encoding="utf-8",
            )

            with self.assertRaisesRegex(ValueError, r"Missing MAM-simple verse for gn 1:2"):
                research_troublemakers.run(
                    SimpleNamespace(
                        troubles_in=troubles_in,
                        wlc422_kq_u_dir=wlc422_dir,
                        uxlc_dir=uxlc_dir,
                        mam_simple_dir=mam_simple_dir,
                        out=out_path,
                    )
                )

            self.assertFalse(out_path.exists())

    def test_run_missing_wlc422_raises_fail_fast(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            mam_simple_dir = base / "mam-simple"
            out_path = base / "out" / "research-troublemakers.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps(
                    {
                        "troublemakers": [
                            {
                                "ref": "gn 1:2",
                                "content": "payload-2",
                            }
                        ]
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text("[]\n", encoding="utf-8")
            (uxlc_dir / "Genesis.xml").write_text(
                """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Tanach>
  <c n=\"1\">
    <v n=\"2\">
      <w>וְהָאָ֗רֶץ</w>
    </v>
  </c>
</Tanach>
""",
                encoding="utf-8",
            )
            (mam_simple_dir / "Gen.json").write_text(
                json.dumps(
                    {
                        "versification-tradition": "vtbhs",
                        "contents": [
                            {
                                "type": "book39",
                                "osisID": "Gen",
                                "contents": [
                                    {
                                        "type": "chapter",
                                        "osisID": "Gen.1",
                                        "contents": [
                                            {
                                                "type": "verse",
                                                "osisID": "Gen.1.2",
                                                "contents": [{"type": "text", "text": "וְהָאָ֗רֶץ"}],
                                            }
                                        ],
                                    }
                                ],
                            }
                        ],
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            with self.assertRaisesRegex(ValueError, r"Missing wlc422-kq-u verse for gn 1:2"):
                research_troublemakers.run(
                    SimpleNamespace(
                        troubles_in=troubles_in,
                        wlc422_kq_u_dir=wlc422_dir,
                        uxlc_dir=uxlc_dir,
                        mam_simple_dir=mam_simple_dir,
                        out=out_path,
                    )
                )

            self.assertFalse(out_path.exists())

    def test_run_missing_uxlc_raises_fail_fast(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            mam_simple_dir = base / "mam-simple"
            out_path = base / "out" / "research-troublemakers.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps(
                    {
                        "troublemakers": [
                            {
                                "ref": "gn 1:2",
                                "content": "payload-2",
                            }
                        ]
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text(
                json.dumps(
                    [
                        {
                            "bcv": "gn1:2",
                            "vels": ["וְהָאָ֗רֶץ"],
                        }
                    ],
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (uxlc_dir / "Genesis.xml").write_text(
                """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Tanach>
  <c n=\"1\">
    <v n=\"1\">
      <w>בְּרֵאשִׁ֖ית</w>
    </v>
  </c>
</Tanach>
""",
                encoding="utf-8",
            )
            (mam_simple_dir / "Gen.json").write_text(
                json.dumps(
                    {
                        "versification-tradition": "vtbhs",
                        "contents": [
                            {
                                "type": "book39",
                                "osisID": "Gen",
                                "contents": [
                                    {
                                        "type": "chapter",
                                        "osisID": "Gen.1",
                                        "contents": [
                                            {
                                                "type": "verse",
                                                "osisID": "Gen.1.2",
                                                "contents": [{"type": "text", "text": "וְהָאָ֗רֶץ"}],
                                            }
                                        ],
                                    }
                                ],
                            }
                        ],
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )

            with self.assertRaisesRegex(ValueError, r"Missing UXLC verse for gn 1:2"):
                research_troublemakers.run(
                    SimpleNamespace(
                        troubles_in=troubles_in,
                        wlc422_kq_u_dir=wlc422_dir,
                        uxlc_dir=uxlc_dir,
                        mam_simple_dir=mam_simple_dir,
                        out=out_path,
                    )
                )

            self.assertFalse(out_path.exists())

    def test_run_creates_output_path_and_writes_expected_top_level_fields(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            mam_simple_dir = base / "mam-simple"
            out_path = base / "nested" / "deep" / "research-troublemakers.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)
            mam_simple_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps({"troublemakers": []}, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text("[]\n", encoding="utf-8")
            (mam_simple_dir / "Gen.json").write_text(
                json.dumps({"versification-tradition": "vtbhs", "contents": []}, ensure_ascii=False, indent=2)
                + "\n",
                encoding="utf-8",
            )

            research_troublemakers.run(
                SimpleNamespace(
                    troubles_in=troubles_in,
                    wlc422_kq_u_dir=wlc422_dir,
                    uxlc_dir=uxlc_dir,
                    mam_simple_dir=mam_simple_dir,
                    out=out_path,
                )
            )

            self.assertTrue(out_path.exists())
            payload = json.loads(out_path.read_text(encoding="utf-8"))
            self.assertIn("provenance", payload)
            self.assertIn("summary", payload)
            self.assertIn("troublemakers", payload)
            self.assertEqual(payload["summary"]["troublemakers"], 0)


if __name__ == "__main__":
    unittest.main()