# Initially generated by GitHub Copilot.

from __future__ import annotations

import json
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path
from tempfile import TemporaryDirectory
from types import SimpleNamespace

from accgram.hebrew_verse_sanitize import sanitize_verse_text_payload
from accgram import research_troublemakers
from accgram import wlc_uxlc_diff


class TestAccgramResearchTroublemakers(unittest.TestCase):
    def test_diff_wlc_uxlc_simplifies_uxlc_note_only_delta(self):
        diff = wlc_uxlc_diff.diff_wlc_uxlc(
            {"vels": ["foo"]},
            [{"text": "foo", "note": "bar"}],
        )

        self.assertEqual(diff, [{"uxlc_adds_note": "bar"}])

    def test_diff_wlc_uxlc_simplifies_note_only_delta(self):
        diff = wlc_uxlc_diff.diff_wlc_uxlc(
            {"vels": [{"word": "foo", "notes": ["]Q", "]n", "]p"]}]},
            ["foo"],
        )

        self.assertEqual(diff, [{"wlc_adds_notes": ["]Q", "]n", "]p"]}])

    def test_diff_wlc_uxlc_reports_token_changes(self):
        diff = wlc_uxlc_diff.diff_wlc_uxlc(
            {"vels": ["a", "b", "c"]},
            ["a", "x", "c"],
        )

        self.assertEqual(diff, [{"wlc422": ["b"], "uxlc": ["x"]}])

    def test_to_xmlish_word_preserves_text_after_inline_x_child(self):
        element = ET.fromstring("<w>פֶ֛<x>t</x>לִאי׃</w>")

        node = research_troublemakers._to_xmlish_verse_child(element)
        node = sanitize_verse_text_payload(node)

        self.assertIsInstance(node, dict)
        self.assertEqual(node, {"text": "פ֛לאי׃", "note": "t"})

    def test_sanitize_keeps_only_last_meteg_in_last_word(self):
        wlc422_verse = {
            "bcv": "gn1:1",
            "vels": ["אֽב", "גֽדֽה"],
        }
        uxlc_nodes = ["אֽב", "גֽדֽה"]

        wlc_clean = sanitize_verse_text_payload(wlc422_verse)
        uxlc_clean = sanitize_verse_text_payload(uxlc_nodes)

        self.assertEqual(wlc_clean["vels"], ["אב", "גדֽה"])
        self.assertEqual(uxlc_clean, ["אב", "גדֽה"])

    def test_run_happy_path_enriches_both_sources(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            out_path = base / "out" / "research-troublemakers.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps(
                    {
                        "troublemakers": [
                            {
                                "ref": "gn 1:1",
                                "content": "payload",
                            }
                        ]
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text(
                json.dumps(
                    [
                        {
                            "bcv": "gn1:1",
                            "vels": ["בְּרֵאשִׁ֖ית", {"sam_pe_inun": "P"}, "בָּרָ֣א"],
                        }
                    ],
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (uxlc_dir / "Genesis.xml").write_text(
                """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Tanach>
  <c n=\"1\">
    <v n=\"1\">
      <w>בְּרֵאשִׁ֖ית<s t=\"large\">ע</s><x>5</x></w>
      <k>כתיב</k>
      <q>קְרֵי</q>
      <samekh/>
    </v>
  </c>
</Tanach>
""",
                encoding="utf-8",
            )

            research_troublemakers.run(
                SimpleNamespace(
                    troubles_in=troubles_in,
                    wlc422_kq_u_dir=wlc422_dir,
                    uxlc_dir=uxlc_dir,
                    out=out_path,
                )
            )

            self.assertTrue(out_path.exists())
            payload = json.loads(out_path.read_text(encoding="utf-8"))
            self.assertEqual(
                payload["provenance"],
                "This file was generated by wlc-utils/py/accgram/research_troublemakers.py.",
            )
            self.assertEqual(payload["summary"]["troublemakers"], 1)
            self.assertEqual(payload["summary"]["wlc422_kq_u_found"], 1)
            self.assertEqual(payload["summary"]["uxlc_found"], 1)

            row = payload["troublemakers"][0]
            self.assertEqual(row["ref"], "gn 1:1")
            self.assertEqual(row["wlc422_kq_u_verse"]["vels"][0], "בראש֖ית")
            self.assertEqual(row["wlc422_kq_u_verse"]["vels"][1], "בר֣א")
            self.assertIsInstance(row["diff_wlc_uxlc"], list)
            self.assertGreaterEqual(len(row["diff_wlc_uxlc"]), 1)
            self.assertFalse(
                any(
                    isinstance(token, dict) and set(token.keys()) == {"sam_pe_inun"}
                    for token in row["wlc422_kq_u_verse"]["vels"]
                )
            )

            xmlish = row["uxlc_verse"]
            self.assertEqual(xmlish[0]["tag"], "w")
            self.assertEqual(xmlish[0]["text"], "בראש֖ית")
            self.assertEqual(xmlish[1], "קרי")
            self.assertFalse(
                any(
                    isinstance(node, dict) and node.get("tag") in {"pe", "samekh"}
                    for node in xmlish
                )
            )
            self.assertEqual(xmlish[0]["children"][0]["tag"], "s")
            self.assertEqual(xmlish[0]["children"][0]["attrs"]["t"], "large")
            self.assertEqual(xmlish[0]["children"][1]["tag"], "x")
            self.assertEqual(xmlish[0]["children"][1]["text"], "5")

    def test_run_missing_in_one_source_sets_null_and_increments_counter(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            out_path = base / "out" / "research-troublemakers.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps(
                    {
                        "troublemakers": [
                            {
                                "ref": "gn 1:2",
                                "content": "payload-2",
                            }
                        ]
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text("[]\n", encoding="utf-8")
            (uxlc_dir / "Genesis.xml").write_text(
                """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Tanach>
  <c n=\"1\">
    <v n=\"2\">
      <w>וְהָאָ֗רֶץ</w>
    </v>
  </c>
</Tanach>
""",
                encoding="utf-8",
            )

            research_troublemakers.run(
                SimpleNamespace(
                    troubles_in=troubles_in,
                    wlc422_kq_u_dir=wlc422_dir,
                    uxlc_dir=uxlc_dir,
                    out=out_path,
                )
            )

            payload = json.loads(out_path.read_text(encoding="utf-8"))
            self.assertEqual(payload["summary"]["wlc422_kq_u_missing"], 1)
            self.assertEqual(payload["summary"]["uxlc_missing"], 0)

            row = payload["troublemakers"][0]
            self.assertIsNone(row["wlc422_kq_u_verse"])
            self.assertEqual(row["uxlc_verse"], ["והא֗רץ"])
            self.assertIsNone(row["diff_wlc_uxlc"])

    def test_run_creates_output_path_and_writes_expected_top_level_fields(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            out_path = base / "nested" / "deep" / "research-troublemakers.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps({"troublemakers": []}, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text("[]\n", encoding="utf-8")

            research_troublemakers.run(
                SimpleNamespace(
                    troubles_in=troubles_in,
                    wlc422_kq_u_dir=wlc422_dir,
                    uxlc_dir=uxlc_dir,
                    out=out_path,
                )
            )

            self.assertTrue(out_path.exists())
            payload = json.loads(out_path.read_text(encoding="utf-8"))
            self.assertIn("provenance", payload)
            self.assertIn("summary", payload)
            self.assertIn("troublemakers", payload)
            self.assertEqual(payload["summary"]["troublemakers"], 0)


if __name__ == "__main__":
    unittest.main()