# Initially generated by GitHub Copilot.

from __future__ import annotations

import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest.mock import patch

from accgram import run_orig


class TestAccgramRunOrig(unittest.TestCase):
    def test_run_orig_passes_pre_normalized_input_through(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            in_dir = base / "in"
            out_dir = base / "out"
            stderr_dir = base / "err"
            goerwitz_bin = base / "accents"

            in_dir.mkdir(parents=True, exist_ok=True)
            goerwitz_bin.write_text("fake-binary", encoding="utf-8")
            payload = "Obadiah\n1:1 X:AZO73WN\n"
            (in_dir / "wlc_422_ps_ob.txt").write_text(payload, encoding="utf-8")

            seen_payloads: list[str] = []

            class FakeCompletedProcess:
                def __init__(self, stdout: bytes, stderr: bytes, returncode: int = 0):
                    self.stdout = stdout
                    self.stderr = stderr
                    self.returncode = returncode

            def fake_run(cmd, input, capture_output, check):
                self.assertEqual(cmd[0], "wsl")
                self.assertTrue(capture_output)
                self.assertFalse(check)
                seen_payloads.append(input.decode("utf-8"))
                return FakeCompletedProcess(stdout=b"", stderr=b"")

            with patch("accgram.run_orig.subprocess.run", side_effect=fake_run):
                run_orig.run_orig(
                    in_dir=in_dir,
                    out_dir=out_dir,
                    stderr_dir=stderr_dir,
                    goerwitz_bin=goerwitz_bin,
                )

            self.assertEqual(seen_payloads, [payload])

    def test_run_orig_writes_stdout_and_stderr_sidecars(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            in_dir = base / "in"
            out_dir = base / "out"
            stderr_dir = base / "err"
            goerwitz_bin = base / "accents"

            in_dir.mkdir(parents=True, exist_ok=True)
            goerwitz_bin.write_text("fake-binary", encoding="utf-8")

            (in_dir / "wlc_422_ps_ob.txt").write_text("Obadiah\n1:1 X\n", encoding="utf-8")
            (in_dir / "wlc_422_ps_gn.txt").write_text("Genesis\n1:1 Y\n", encoding="utf-8")

            calls: list[list[str]] = []

            def fake_run(cmd, input, capture_output, check):
                self.assertEqual(cmd[0], "wsl")
                self.assertEqual(cmd[2], "-p")
                self.assertTrue(capture_output)
                self.assertFalse(check)
                calls.append(cmd)

                class FakeCompletedProcess:
                    def __init__(self, stdout: bytes, stderr: bytes, returncode: int = 0):
                        self.stdout = stdout
                        self.stderr = stderr
                        self.returncode = returncode

                payload = input.decode("utf-8")
                if "Obadiah" in payload:
                    return FakeCompletedProcess(stdout=b"TREE\n", stderr=b"")
                return FakeCompletedProcess(stdout=b"", stderr=b"goerwitz warning\n")

            with patch("accgram.run_orig.subprocess.run", side_effect=fake_run):
                result = run_orig.run_orig(
                    in_dir=in_dir,
                    out_dir=out_dir,
                    stderr_dir=stderr_dir,
                    goerwitz_bin=goerwitz_bin,
                )

            self.assertEqual(result.input_count, 2)
            self.assertEqual(result.output_count, 2)
            self.assertEqual(result.nonempty_output_count, 1)
            self.assertEqual(result.stderr_nonempty_count, 1)
            self.assertEqual(result.nonzero_exit_count, 0)
            self.assertEqual(len(calls), 2)

            self.assertEqual((out_dir / "wlc_422_ps_ob_ag.txt").read_text(encoding="utf-8"), "TREE\n")
            self.assertEqual(
                (stderr_dir / "wlc_422_ps_gn_ag.stderr.txt").read_text(encoding="utf-8"),
                "goerwitz warning\n",
            )

    def test_run_orig_reports_nonzero_exit_with_empty_stderr(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            in_dir = base / "in"
            out_dir = base / "out"
            stderr_dir = base / "err"
            goerwitz_bin = base / "accents"

            in_dir.mkdir(parents=True, exist_ok=True)
            goerwitz_bin.write_text("fake-binary", encoding="utf-8")
            (in_dir / "wlc_422_ps_ob.txt").write_text("Obadiah\n1:1 X\n", encoding="utf-8")

            class FakeCompletedProcess:
                def __init__(self):
                    self.stdout = b""
                    self.stderr = b""
                    self.returncode = 7

            with patch("accgram.run_orig.subprocess.run", return_value=FakeCompletedProcess()):
                result = run_orig.run_orig(
                    in_dir=in_dir,
                    out_dir=out_dir,
                    stderr_dir=stderr_dir,
                    goerwitz_bin=goerwitz_bin,
                )

            self.assertEqual(result.nonzero_exit_count, 1)
            sidecar = (stderr_dir / "wlc_422_ps_ob_ag.stderr.txt").read_text(encoding="utf-8")
            self.assertIn("goerwitz exited with code 7", sidecar)


if __name__ == "__main__":
    unittest.main()