# Initially generated by GitHub Copilot.

from __future__ import annotations

import json
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from types import SimpleNamespace
from unittest.mock import patch

from accgram import run_goerwitz


class TestAccgramRunGoerwitz(unittest.TestCase):
    def test_run_goerwitz_passes_pre_normalized_input_through(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            in_dir = base / "in"
            out_dir = base / "out"
            stderr_dir = base / "err"
            goerwitz_bin = base / "accents"

            in_dir.mkdir(parents=True, exist_ok=True)
            goerwitz_bin.write_text("fake-binary", encoding="utf-8")
            payload = "Obadiah\n1:1 X:AZO73WN\n"
            (in_dir / "wlc_422_ps_ob.txt").write_text(payload, encoding="utf-8")

            seen_payloads: list[str] = []

            class FakeCompletedProcess:
                def __init__(self, stdout: bytes, stderr: bytes, returncode: int = 0):
                    self.stdout = stdout
                    self.stderr = stderr
                    self.returncode = returncode

            def fake_run(cmd, input, capture_output, check):
                self.assertEqual(cmd[0], "wsl")
                self.assertTrue(capture_output)
                self.assertFalse(check)
                seen_payloads.append(input.decode("utf-8"))
                return FakeCompletedProcess(stdout=b"", stderr=b"")

            with patch("accgram.run_goerwitz.subprocess.run", side_effect=fake_run):
                run_goerwitz.run_goerwitz_binary(
                    in_dir=in_dir,
                    out_dir=out_dir,
                    stderr_dir=stderr_dir,
                    goerwitz_bin=goerwitz_bin,
                )

            self.assertEqual(seen_payloads, [payload])

    def test_run_goerwitz_writes_stdout_and_stderr_sidecars(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            in_dir = base / "in"
            out_dir = base / "out"
            stderr_dir = base / "err"
            goerwitz_bin = base / "accents"

            in_dir.mkdir(parents=True, exist_ok=True)
            goerwitz_bin.write_text("fake-binary", encoding="utf-8")

            (in_dir / "wlc_422_ps_ob.txt").write_text("Obadiah\n1:1 X\n", encoding="utf-8")
            (in_dir / "wlc_422_ps_gn.txt").write_text("Genesis\n1:1 Y\n", encoding="utf-8")

            calls: list[list[str]] = []

            def fake_run(cmd, input, capture_output, check):
                self.assertEqual(cmd[0], "wsl")
                self.assertEqual(cmd[2], "-p")
                self.assertTrue(capture_output)
                self.assertFalse(check)
                calls.append(cmd)

                class FakeCompletedProcess:
                    def __init__(self, stdout: bytes, stderr: bytes, returncode: int = 0):
                        self.stdout = stdout
                        self.stderr = stderr
                        self.returncode = returncode

                payload = input.decode("utf-8")
                if "Obadiah" in payload:
                    return FakeCompletedProcess(stdout=b"TREE\n", stderr=b"")
                return FakeCompletedProcess(stdout=b"", stderr=b"goerwitz warning\n")

            with patch("accgram.run_goerwitz.subprocess.run", side_effect=fake_run):
                result = run_goerwitz.run_goerwitz_binary(
                    in_dir=in_dir,
                    out_dir=out_dir,
                    stderr_dir=stderr_dir,
                    goerwitz_bin=goerwitz_bin,
                )

            self.assertEqual(result.input_count, 2)
            self.assertEqual(result.output_count, 2)
            self.assertEqual(result.nonempty_output_count, 1)
            self.assertEqual(result.stderr_nonempty_count, 1)
            self.assertEqual(result.nonzero_exit_count, 0)
            self.assertEqual(len(calls), 2)

            self.assertEqual((out_dir / "wlc_422_ps_ob_ag.txt").read_text(encoding="utf-8"), "TREE\n")
            self.assertEqual(
                (stderr_dir / "wlc_422_ps_gn_ag.stderr.txt").read_text(encoding="utf-8"),
                "goerwitz warning\n",
            )

    def test_run_goerwitz_reports_nonzero_exit_with_empty_stderr(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            in_dir = base / "in"
            out_dir = base / "out"
            stderr_dir = base / "err"
            goerwitz_bin = base / "accents"

            in_dir.mkdir(parents=True, exist_ok=True)
            goerwitz_bin.write_text("fake-binary", encoding="utf-8")
            (in_dir / "wlc_422_ps_ob.txt").write_text("Obadiah\n1:1 X\n", encoding="utf-8")

            class FakeCompletedProcess:
                def __init__(self):
                    self.stdout = b""
                    self.stderr = b""
                    self.returncode = 7

            with patch("accgram.run_goerwitz.subprocess.run", return_value=FakeCompletedProcess()):
                result = run_goerwitz.run_goerwitz_binary(
                    in_dir=in_dir,
                    out_dir=out_dir,
                    stderr_dir=stderr_dir,
                    goerwitz_bin=goerwitz_bin,
                )

            self.assertEqual(result.nonzero_exit_count, 1)
            sidecar = (stderr_dir / "wlc_422_ps_ob_ag.stderr.txt").read_text(encoding="utf-8")
            self.assertIn("goerwitz exited with code 7", sidecar)

    def test_run_goerwitz_writes_missing_verses_json(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            in_dir = base / "in"
            out_dir = base / "out"
            stderr_dir = base / "err"
            goerwitz_bin = base / "accents"

            in_dir.mkdir(parents=True, exist_ok=True)
            goerwitz_bin.write_text("fake-binary", encoding="utf-8")

            (in_dir / "wlc_422_ps_ob.txt").write_text("Obadiah\n1:1 Missing verse payload\n1:2 Present verse payload\n", encoding="utf-8")
            (in_dir / "wlc_422_ps_gn.txt").write_text("Genesis\n1:1 Present verse payload\n", encoding="utf-8")

            class FakeCompletedProcess:
                def __init__(self, stdout: bytes, stderr: bytes, returncode: int = 0):
                    self.stdout = stdout
                    self.stderr = stderr
                    self.returncode = returncode

            def fake_run(cmd, input, capture_output, check):
                self.assertEqual(cmd[0], "wsl")
                self.assertTrue(capture_output)
                self.assertFalse(check)
                payload = input.decode("utf-8")
                if payload.startswith("Obadiah"):
                    return FakeCompletedProcess(stdout=b"Obadiah 1:2\n0 tree\n", stderr=b"")
                return FakeCompletedProcess(stdout=b"Genesis 1:1\n0 tree\n", stderr=b"")

            def fake_write_stderr_summary(stderr_dir, summary_path):
                summary_path.parent.mkdir(parents=True, exist_ok=True)
                summary_path.write_text("{}\n", encoding="utf-8")
                return SimpleNamespace(
                    summary_path=summary_path,
                    files_scanned=2,
                    files_with_nonempty_stderr=0,
                    total_stderr_lines=0,
                    total_unique_verse_messages=0,
                    total_unique_non_verse_messages=0,
                )

            with patch("accgram.run_goerwitz.subprocess.run", side_effect=fake_run), patch(
                "accgram.run_goerwitz.write_stderr_summary", side_effect=fake_write_stderr_summary
            ):
                run_goerwitz.run(
                    SimpleNamespace(
                        in_dir=in_dir,
                        out_dir=out_dir,
                        stderr_dir=stderr_dir,
                        goerwitz_bin=goerwitz_bin,
                    )
                )

            missing_path = out_dir / "_missing_verses.json"
            payload = json.loads(missing_path.read_text(encoding="utf-8"))
            self.assertEqual(payload["artifacts_description"], "missing verses from goerwitz *_ag.txt outputs")
            self.assertEqual(payload["summary"]["missing_verses"], 1)
            self.assertEqual(payload["summary"]["books_with_missing_verses"], 1)
            self.assertEqual(
                payload["missing_verses"],
                [
                    {
                        "ref": "ob 1:1",
                        "content": "Missing verse payload",
                        "output_file": "wlc_422_ps_ob_ag.txt",
                    }
                ],
            )

    def test_write_stderr_summary_aggregates_messages(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            stderr_dir = base / "err"
            summary_path = stderr_dir / "_summary.stderr.json"
            stderr_dir.mkdir(parents=True, exist_ok=True)

            (stderr_dir / "b_ag.stderr.txt").write_text(
                "accents warning 3 (yyparse): general parsing error   Obadiah 1:2\n"
                "goerwitz exited with code 7 and produced no stderr output.\n",
                encoding="utf-8",
            )
            (stderr_dir / "a_ag.stderr.txt").write_text(
                "accents warning 3 (yyparse): general parsing error Obadiah 1:2\n"
                "accents warning 6 (yyparse): verse is missing sof pasuq, Obadiah 1:2\n",
                encoding="utf-8",
            )
            (stderr_dir / "z_ag.stderr.txt").write_text("", encoding="utf-8")

            summary_result = run_goerwitz.write_stderr_summary(
                stderr_dir=stderr_dir,
                summary_path=summary_path,
            )

            self.assertEqual(summary_result.files_scanned, 3)
            self.assertEqual(summary_result.files_with_nonempty_stderr, 2)
            self.assertEqual(summary_result.total_stderr_lines, 4)
            self.assertEqual(summary_result.total_unique_verse_messages, 2)
            self.assertEqual(summary_result.total_unique_non_verse_messages, 1)

            summary = json.loads(summary_path.read_text(encoding="utf-8"))
            self.assertEqual(summary["file_counters"]["files_scanned"], 3)
            self.assertEqual(summary["file_counters"]["files_with_nonempty_stderr"], 2)
            self.assertEqual(summary["file_counters"]["total_stderr_lines"], 4)

            verse_rows = summary["verse_message_aggregates"]
            self.assertEqual(len(verse_rows), 1)
            self.assertEqual(verse_rows[0]["verse_ref"], "ob 1:2")
            self.assertEqual(verse_rows[0]["standard_sof_pasuq_error_count"], 2)
            self.assertNotIn("messages", verse_rows[0])

            non_verse_rows = summary["non_verse_message_aggregates"]
            self.assertEqual(len(non_verse_rows), 1)
            self.assertEqual(
                non_verse_rows[0]["message"],
                "goerwitz exited with code 7 and produced no stderr output.",
            )
            self.assertEqual(non_verse_rows[0]["count"], 1)

            per_file = summary["per_file_counters"]
            self.assertEqual([row["file"] for row in per_file], ["a_ag.stderr.txt", "b_ag.stderr.txt", "z_ag.stderr.txt"])


if __name__ == "__main__":
    unittest.main()