# Initially generated by GitHub Copilot.

from __future__ import annotations

import json
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from types import SimpleNamespace

from accgram import research_troublemakers


class TestAccgramResearchTroublemakers(unittest.TestCase):
    def test_run_happy_path_enriches_both_sources(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            out_path = base / "out" / "research-troublemakers.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps(
                    {
                        "troublemakers": [
                            {
                                "ref": "gn 1:1",
                                "content": "payload",
                            }
                        ]
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text(
                json.dumps(
                    [
                        {
                            "bcv": "gn1:1",
                            "vels": ["בְּרֵאשִׁ֖ית", "בָּרָ֣א"],
                        }
                    ],
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (uxlc_dir / "Genesis.xml").write_text(
                """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Tanach>
  <c n=\"1\">
    <v n=\"1\">
      <w>בְּרֵאשִׁ֖ית<s t=\"large\">ע</s><x>5</x></w>
      <k>כתיב</k>
      <q>קְרֵי</q>
      <samekh/>
    </v>
  </c>
</Tanach>
""",
                encoding="utf-8",
            )

            research_troublemakers.run(
                SimpleNamespace(
                    troubles_in=troubles_in,
                    wlc422_kq_u_dir=wlc422_dir,
                    uxlc_dir=uxlc_dir,
                    out=out_path,
                )
            )

            self.assertTrue(out_path.exists())
            payload = json.loads(out_path.read_text(encoding="utf-8"))
            self.assertEqual(
                payload["provenance"],
                "This file was generated by wlc-utils/py/accgram/research_troublemakers.py.",
            )
            self.assertEqual(payload["summary"]["troublemakers"], 1)
            self.assertEqual(payload["summary"]["wlc422_kq_u_found"], 1)
            self.assertEqual(payload["summary"]["uxlc_found"], 1)

            row = payload["troublemakers"][0]
            self.assertEqual(row["ref"], "gn 1:1")
            self.assertEqual(row["wlc422_kq_u_verse"]["bcv"], "gn1:1")
            self.assertEqual(row["uxlc_context"]["xml_file"], "Genesis.xml")

            xmlish = row["uxlc_verse_xmlish"]
            self.assertEqual(xmlish[0]["tag"], "w")
            self.assertEqual(xmlish[1]["tag"], "k")
            self.assertEqual(xmlish[2]["tag"], "q")
            self.assertEqual(xmlish[3]["tag"], "samekh")
            self.assertEqual(xmlish[0]["children"][0]["tag"], "s")
            self.assertEqual(xmlish[0]["children"][0]["attrs"]["t"], "large")
            self.assertEqual(xmlish[0]["children"][1]["tag"], "x")

    def test_run_missing_in_one_source_sets_null_and_increments_counter(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            out_path = base / "out" / "research-troublemakers.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps(
                    {
                        "troublemakers": [
                            {
                                "ref": "gn 1:2",
                                "content": "payload-2",
                            }
                        ]
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text("[]\n", encoding="utf-8")
            (uxlc_dir / "Genesis.xml").write_text(
                """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Tanach>
  <c n=\"1\">
    <v n=\"2\">
      <w>וְהָאָ֗רֶץ</w>
    </v>
  </c>
</Tanach>
""",
                encoding="utf-8",
            )

            research_troublemakers.run(
                SimpleNamespace(
                    troubles_in=troubles_in,
                    wlc422_kq_u_dir=wlc422_dir,
                    uxlc_dir=uxlc_dir,
                    out=out_path,
                )
            )

            payload = json.loads(out_path.read_text(encoding="utf-8"))
            self.assertEqual(payload["summary"]["wlc422_kq_u_missing"], 1)
            self.assertEqual(payload["summary"]["uxlc_missing"], 0)

            row = payload["troublemakers"][0]
            self.assertIsNone(row["wlc422_kq_u_verse"])
            self.assertEqual(row["uxlc_verse_xmlish"], ["וְהָאָ֗רֶץ"])
            self.assertIsNotNone(row["uxlc_context"])

    def test_run_creates_output_path_and_writes_expected_top_level_fields(self):
        with TemporaryDirectory() as tmp_dir:
            base = Path(tmp_dir)
            troubles_in = base / "in" / "_troublemakers.json"
            wlc422_dir = base / "wlc422-kq-u"
            uxlc_dir = base / "uxlc"
            out_path = base / "nested" / "deep" / "research-troublemakers.json"

            troubles_in.parent.mkdir(parents=True, exist_ok=True)
            wlc422_dir.mkdir(parents=True, exist_ok=True)
            uxlc_dir.mkdir(parents=True, exist_ok=True)

            troubles_in.write_text(
                json.dumps({"troublemakers": []}, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            (wlc422_dir / "1verses_00_gn.json").write_text("[]\n", encoding="utf-8")

            research_troublemakers.run(
                SimpleNamespace(
                    troubles_in=troubles_in,
                    wlc422_kq_u_dir=wlc422_dir,
                    uxlc_dir=uxlc_dir,
                    out=out_path,
                )
            )

            self.assertTrue(out_path.exists())
            payload = json.loads(out_path.read_text(encoding="utf-8"))
            self.assertIn("provenance", payload)
            self.assertIn("summary", payload)
            self.assertIn("troublemakers", payload)
            self.assertEqual(payload["summary"]["troublemakers"], 0)


if __name__ == "__main__":
    unittest.main()