# Initially generated by GitHub Copilot.
"""Helpers for stable generation provenance breadcrumbs."""

from pathlib import Path

_SIDECAR_NAME = "provenance.md"


def generated_by_text(generator_file: str) -> str:
    """Return a stable human-readable generated-by string."""
    return f"This file was generated by {_display_path(generator_file)}."


def generated_html_comment(generator_file: str) -> str:
    """Return an HTML comment payload for a generated file."""
    return f"Do not edit by hand. {generated_by_text(generator_file)}"


def with_json_provenance(root, generator_file: str):
    """Return a JSON root dict with provenance inserted as the first key."""
    if not isinstance(root, dict):
        raise TypeError("JSON provenance injection requires a top-level dict")
    rest = {key: value for key, value in root.items() if key != "provenance"}
    return {"provenance": generated_by_text(generator_file), **rest}


def write_directory_provenance(
    dir_path: str,
    generator_file: str,
    artifacts_description: str,
    sidecar_name: str = _SIDECAR_NAME,
):
    """Write a provenance sidecar for a directory of generated artifacts."""
    out_path = Path(dir_path) / sidecar_name
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as out_fp:
        out_fp.write(
            directory_provenance_markdown(generator_file, artifacts_description)
        )


def directory_provenance_markdown(
    generator_file: str, artifacts_description: str
) -> str:
    """Return Markdown text for a directory-level provenance sidecar."""
    description = artifacts_description.rstrip(".")
    return "\n".join(
        (
            "<!-- Initially generated by GitHub Copilot. -->",
            "# Provenance",
            "",
            f"This directory contains generated {description}.",
            generated_by_text(generator_file),
            "Payload files in this directory remain in their native data format, so provenance is recorded here rather than inside each file.",
            "",
        )
    )


def _display_path(generator_file: str) -> str:
    generator_path = Path(generator_file).resolve()
    repo_root = Path(__file__).resolve().parents[2]
    repo_name = repo_root.name
    repos_root = repo_root.parent
    try:
        repos_rel = generator_path.relative_to(repos_root).as_posix()
        if repos_rel.startswith(f"{repo_name}/"):
            return repos_rel
    except ValueError:
        pass
    try:
        repo_rel = generator_path.relative_to(repo_root).as_posix()
    except ValueError as exc:
        raise ValueError(
            f"Generator path is outside both {repo_root} and {repos_root}: {generator_path}"
        ) from exc
    return f"{repo_name}/{repo_rel}"
