# Initially generated by GitHub Copilot.
"""Helpers for stable generation provenance breadcrumbs."""

from pathlib import Path

_SIDECAR_NAME = "provenance.md"


def generated_by_text(generator_file: str, repo_name: str | None = None) -> str:
    """Return a stable human-readable generated-by string."""
    return f"This file was generated by {_display_path(generator_file, repo_name)}."


def generated_html_comment(generator_file: str, repo_name: str | None = None) -> str:
    """Return an HTML comment payload for a generated file."""
    return f"Do not edit by hand. {generated_by_text(generator_file, repo_name)}"


def with_json_provenance(root, generator_file: str, repo_name: str | None = None):
    """Return a JSON root dict with provenance inserted as the first key."""
    if not isinstance(root, dict):
        raise TypeError("JSON provenance injection requires a top-level dict")
    rest = {key: value for key, value in root.items() if key != "provenance"}
    return {"provenance": generated_by_text(generator_file, repo_name), **rest}


def write_directory_provenance(
    dir_path: str,
    generator_file: str,
    artifacts_description: str,
    sidecar_name: str = _SIDECAR_NAME,
    repo_name: str | None = None,
    newline: str = "",
):
    """Write a provenance sidecar for a directory of generated artifacts."""
    out_path = Path(dir_path) / sidecar_name
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8", newline=newline) as out_fp:
        out_fp.write(
            directory_provenance_markdown(
                generator_file, artifacts_description, repo_name
            )
        )


def directory_provenance_markdown(
    generator_file: str, artifacts_description: str, repo_name: str | None = None
) -> str:
    """Return Markdown text for a directory-level provenance sidecar."""
    description = artifacts_description.rstrip(".")
    return "\n".join(
        (
            "<!-- Initially generated by GitHub Copilot. -->",
            "# Provenance",
            "",
            f"This directory contains generated {description}.",
            generated_by_text(generator_file, repo_name),
            "Payload files in this directory remain in their native data format, so provenance is recorded here rather than inside each file.",
            "",
        )
    )


def _display_path(generator_file: str, repo_name: str | None = None) -> str:
    """Repo-relative breadcrumb for ``generator_file``.

    The top-level path segment is ``repo_name`` when supplied, else the checkout
    directory name (``repo_root.name``).  Passing the logical name lets a
    consuming repo whose checkout directory may differ from its name -- most
    notably a git worktree rooted at ``.../.claude/worktrees/agent-xxx`` rather
    than literally ``wlc-utils`` -- still emit stable ``wlc-utils/...`` paths.
    """
    generator_path = Path(generator_file).resolve()
    repo_root = Path(__file__).resolve().parents[2]
    actual_name = repo_root.name
    logical_name = repo_name if repo_name is not None else actual_name
    repos_root = repo_root.parent
    try:
        repos_rel = generator_path.relative_to(repos_root).as_posix()
        prefix = f"{actual_name}/"
        if repos_rel.startswith(prefix):
            return f"{logical_name}/{repos_rel[len(prefix):]}"
    except ValueError:
        pass
    try:
        repo_rel = generator_path.relative_to(repo_root).as_posix()
    except ValueError as exc:
        raise ValueError(
            f"Generator path is outside both {repo_root} and {repos_root}: {generator_path}"
        ) from exc
    return f"{logical_name}/{repo_rel}"
