# Initially generated by GitHub Copilot.
"""Template-name constants for historical MAM template handling.

Code that only needs modern (non-historical) MAM data should avoid importing
this module.
"""

# SR: strongly related ketiv & qere
# WR: weakly related ketiv & qere
# UR: unrelated ketiv & qere

K1Q1_MCOM = "מ:כו״ק בין שני מקפים"
K1Q2_SR_KQQ = "מ:כו״ק כתיב מילה חדה וקרי תרתין מילין"
K1Q2_SR_QQK = "מ:קו״כ כתיב מילה חדה וקרי תרתין מילין"
K1Q2_SR_BCOM = "מ:כו״ק כתיב מילה חדה וקרי תרתין מילין בין שני מקפים"
K1Q2_WR_KQQ = "מ:כו״ק קרי שונה מהכתיב בשתי מילים"
K1Q2_UR_QQK = "מ:קו״כ קרי שונה מהכתיב בשתי מילים"
K2Q1 = "מ:כו״ק כתיב תרתין מילין וקרי מילה חדה"
K2Q2 = "מ:כו״ק של שתי מילים בהערה אחת"
K3Q3 = "מ:כו״ק של שלוש מילים בהערה אחת"
