# Initially generated by GitHub Copilot.
"""Normalize special ketiv/qere template forms across old and unified names."""

from mb_cmn import hebrew_punctuation as hpu
from mb_cmn import retired_template_names as rtmpln

UNIFIED_SPECIAL_KQ_TEMPLATE_NAME = "מ:כו״ק מיוחד"

# Explicit mapping table. Do not derive sug text from old template names.
_SPECIAL_KQ_SPECS = (
    (
        rtmpln.K1Q1_MCOM,
        "כו״ק בין שני מקפים",
        "k1q1-mcom",
    ),
    (
        rtmpln.K1Q2_SR_KQQ,
        "כו״ק כתיב מילה חדה וקרי תרתין מילין",
        "k1q2-sr-kqq",
    ),
    (
        rtmpln.K1Q2_SR_QQK,
        "קו״כ כתיב מילה חדה וקרי תרתין מילין",
        "k1q2-sr-qqk",
    ),
    (
        rtmpln.K1Q2_SR_BCOM,
        "כו״ק כתיב מילה חדה וקרי תרתין מילין בין שני מקפים",
        "k1q2-sr-bcom",
    ),
    (
        rtmpln.K1Q2_WR_KQQ,
        "כו״ק קרי שונה מהכתיב בשתי מילים",
        "k1q2-wr-kqq",
    ),
    (
        rtmpln.K1Q2_UR_QQK,
        "קו״כ קרי שונה מהכתיב בשתי מילים",
        "k1q2-ur-qqk",
    ),
    (
        rtmpln.K2Q1,
        "כו״ק כתיב תרתין מילין וקרי מילה חדה",
        "k2q1",
    ),
    (
        rtmpln.K2Q2,
        "כו״ק של שתי מילים בהערה אחת",
        "k2q2",
    ),
    (
        rtmpln.K3Q3,
        "כו״ק של שלוש מילים בהערה אחת",
        "k3q3",
    ),
)

OLD_SPECIAL_KQ_TEMPLATE_NAMES = tuple(spec[0] for spec in _SPECIAL_KQ_SPECS)
SPECIAL_KQ_TYPE_KEYS = tuple(spec[2] for spec in _SPECIAL_KQ_SPECS)

_SPECIAL_KQ_TYPE_FROM_OLD_NAME = {spec[0]: spec[2] for spec in _SPECIAL_KQ_SPECS}
_SPECIAL_KQ_SUG_FROM_OLD_NAME = {spec[0]: spec[1] for spec in _SPECIAL_KQ_SPECS}
_SPECIAL_KQ_OLD_NAME_FROM_SUG = {spec[1]: spec[0] for spec in _SPECIAL_KQ_SPECS}

assert len(_SPECIAL_KQ_TYPE_FROM_OLD_NAME) == len(_SPECIAL_KQ_SPECS), (
    _SPECIAL_KQ_TYPE_FROM_OLD_NAME,
)
assert len(_SPECIAL_KQ_OLD_NAME_FROM_SUG) == len(_SPECIAL_KQ_SPECS), (
    _SPECIAL_KQ_OLD_NAME_FROM_SUG,
)


def is_unified_special_kq_template_name(template_name):
    return template_name == UNIFIED_SPECIAL_KQ_TEMPLATE_NAME


def is_old_special_kq_template_name(template_name):
    return template_name in _SPECIAL_KQ_TYPE_FROM_OLD_NAME


def is_special_kq_template_name(template_name):
    return is_old_special_kq_template_name(
        template_name
    ) or is_unified_special_kq_template_name(template_name)


def sug_text_for_old_special_kq_template_name(old_template_name):
    assert is_old_special_kq_template_name(old_template_name), old_template_name
    return _SPECIAL_KQ_SUG_FROM_OLD_NAME[old_template_name]


def _canonical_old_name_for_unified_sug(sug_text):
    assert isinstance(sug_text, str), sug_text
    sug_text = _normalize_sug_text(sug_text)
    assert sug_text in _SPECIAL_KQ_OLD_NAME_FROM_SUG, sug_text
    return _SPECIAL_KQ_OLD_NAME_FROM_SUG[sug_text]


def canonical_special_kq_old_name_from_name_and_sug(template_name, sug_text=None):
    """Return the canonical old template name for a special-kq template call.

    For old-form names this returns template_name itself.
    For unified-form calls (מ:כו״ק מיוחד) this resolves from סוג=... .
    """
    assert is_special_kq_template_name(template_name), template_name
    if is_old_special_kq_template_name(template_name):
        if sug_text is not None:
            assert _normalize_sug_text(
                sug_text
            ) == sug_text_for_old_special_kq_template_name(template_name), (
                template_name,
                sug_text,
            )
        return template_name

    assert is_unified_special_kq_template_name(template_name), template_name
    assert sug_text is not None, template_name
    return _canonical_old_name_for_unified_sug(sug_text)


def canonical_special_kq_type_from_name_and_sug(template_name, sug_text=None):
    """Return canonical k/q subtype key (for example k1q2-sr-kqq)."""
    old_name = canonical_special_kq_old_name_from_name_and_sug(template_name, sug_text)
    return _SPECIAL_KQ_TYPE_FROM_OLD_NAME[old_name]


def maybe_special_kq_type_from_name_and_sug(template_name, sug_text=None):
    """Return canonical subtype for special-kq templates, else None."""
    if not is_special_kq_template_name(template_name):
        return None
    return canonical_special_kq_type_from_name_and_sug(template_name, sug_text)


_Q2_TO_G2 = str.maketrans({'"': hpu.GERSHAYIM})


def _normalize_sug_text(sug_text):
    assert isinstance(sug_text, str), sug_text
    return sug_text.translate(_Q2_TO_G2)


def maybe_canonical_special_kq_old_name_from_name_and_sug(template_name, sug_text=None):
    """Return canonical old special-kq template name, or None if not special-kq."""
    if not is_special_kq_template_name(template_name):
        return None
    return canonical_special_kq_old_name_from_name_and_sug(template_name, sug_text)
