# Initially generated by GitHub Copilot.
"""Small URL percent-encoding helpers for escape-boundary usage."""

from urllib import parse


def pct_path_component(text: str, safe: str = "") -> str:
    """Percent-encode a URL path/title component."""
    return parse.quote(text, safe=safe)


def pct_fragment(text: str, safe: str = "") -> str:
    """Percent-encode a URL fragment payload when needed."""
    return parse.quote(text, safe=safe)


def pct_query(params: dict[str, str | int]) -> str:
    """Percent-encode URL query parameters."""
    return parse.urlencode(params)


def pct_decode(text: str) -> str:
    """Decode a percent-encoded string."""
    return parse.unquote(text)
