# Initially generated by GitHub Copilot.
"""Helpers for constructing UXLC change-record URLs."""

from mb_cmn.url_percent import pct_path_component


def uxlc_release_label(release_date: str) -> str:
    """Return the human-readable release label used by tanach.us."""
    return f"{release_date} - Changes"


def uxlc_release_xml_filename(release_date: str) -> str:
    """Return the XML filename for a UXLC release."""
    return f"{uxlc_release_label(release_date)}.xml"


def uxlc_release_xml_url(release_date: str) -> str:
    """Return the URL of the release XML file."""
    release_label_enc = pct_path_component(uxlc_release_label(release_date))
    return f"https://tanach.us/Changes/{release_label_enc}/{release_label_enc}.xml"


def uxlc_change_url(release_date: str, change_id: str) -> str:
    """Return the URL of a specific change record within a release."""
    return f"{uxlc_release_xml_url(release_date)}?{change_id}"
