# Initially generated by GitHub Copilot.
"""Shared helpers for vendoring sync scripts across sibling repositories."""

from pathlib import Path
import shutil
import subprocess
from typing import Iterable, Sequence


def get_git_info(repo_path: Path) -> tuple[str, str | None]:
    """Return (commit_hash, exact_tag_or_None) for HEAD in repo_path."""
    commit = _git_stdout(repo_path, "rev-parse", "HEAD")

    tag_result = subprocess.run(
        ["git", "-C", str(repo_path), "describe", "--tags", "--exact-match", "HEAD"],
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    tag = tag_result.stdout.strip() if tag_result.returncode == 0 else None
    return commit, tag


def copy_by_intersection(
    src_dir: Path,
    dest_dir: Path,
    *,
    include_suffixes: tuple[str, ...] | None = (".py",),
    strict: bool = True,
    recursive: bool = False,
    exclude_rel_paths: Iterable[str] = (),
) -> list[str]:
    """Copy local files from src_dir to dest_dir by path intersection.

    Iterates files already present in dest_dir, then copies matching source files
    from src_dir using shutil.copy2. Returns sorted copied paths (POSIX form).
    """
    excluded = {rel.replace("\\", "/") for rel in exclude_rel_paths}
    suffixes = None if include_suffixes is None else set(include_suffixes)

    copied: list[str] = []
    local_files = _iter_local_files(dest_dir, recursive=recursive)
    for local_file in local_files:
        rel_path = local_file.relative_to(dest_dir)
        rel_posix = rel_path.as_posix()

        if rel_posix in excluded:
            continue
        if suffixes is not None and local_file.suffix not in suffixes:
            continue

        src_file = src_dir / rel_path
        if not src_file.is_file():
            if strict:
                raise FileNotFoundError(
                    f"{rel_posix} exists locally but not in source {src_dir}"
                )
            continue

        shutil.copy2(src_file, local_file)
        copied.append(rel_posix)

    return copied


def write_provenance(
    dest_dir: Path,
    *,
    source_rel: str,
    copied_files: Sequence[str],
    commit: str,
    tag: str | None,
    date_str: str,
    title: str | None = None,
    removed_paths: Sequence[str] = (),
) -> None:
    """Write standardized provenance.md in dest_dir."""
    normalized_copied = sorted({p.replace("\\", "/") for p in copied_files})
    normalized_removed = sorted({p.replace("\\", "/") for p in removed_paths})

    heading = title if title is not None else f"Provenance of {dest_dir.name}/"
    lines = [
        heading,
        "",
        "These files were copied from a sibling source repository at:",
        "",
        f"  GitRepos-relative path: {source_rel}",
        "",
        "Files copied:",
    ]
    for rel_path in normalized_copied:
        lines.append(f"  {rel_path}")

    if normalized_removed:
        lines.append("")
        lines.append("Legacy paths removed:")
        for rel_path in normalized_removed:
            lines.append(f"  {rel_path}")

    lines.append("")
    lines.append(f"Git commit: {commit}")
    if tag is not None:
        lines.append(f"Git tag:    {tag}")
    lines.append("")
    lines.append(f"Date copied: {date_str}")
    lines.append("")

    provenance_path = dest_dir / "provenance.md"
    provenance_path.write_text("\n".join(lines), encoding="utf-8")


def _git_stdout(repo_path: Path, *args: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo_path), *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=True,
    )
    return result.stdout.strip()


def _iter_local_files(dest_dir: Path, *, recursive: bool) -> list[Path]:
    iterator = dest_dir.rglob("*") if recursive else dest_dir.iterdir()
    files = [
        path for path in iterator if path.is_file() and "__pycache__" not in path.parts
    ]
    return sorted(files, key=lambda path: path.relative_to(dest_dir).as_posix())
